#
# Makefile for the rioproxy network device drivers.
#
ccflags-$(CONFIG_FSM4_AXM) += -DCONFIG_RIOPROXY_ON_BROKEN_CPU
ccflags-$(CONFIG_FSM4_AXM64) += -DCONFIG_RIOPROXY_ON_BROKEN_CPU
obj-$(CONFIG_RIOPROXY) += rioproxy.o
