#
# Generic Hardware Queue framework
#

obj-$(CONFIG_HWQUEUE)		+= hwqueue_core.o		\
					knav_qmss_monitor.o
obj-$(CONFIG_HWQUEUE_TEST)	+= hwqueue_test.o
obj-$(CONFIG_HWQUEUE_KEYSTONE)	+= keystone_hwqueue.o		\
				   keystone_hwqueue_acc.o	\
				   keystone_hwqueue_qos.o