# File: drivers/crypto/bcm/Makefile
#
# Makefile for broadcom IPROC public key acceleration (PKA) driver
#
obj-$(CONFIG_CRYPTO_DEV_IPROC_PKA) := iproc_pka.o
iproc_pka-objs := pka.o q_addsub.o q_dh.o q_div.o q_dsa.o q_ecdsa.o q_ecp.o q_elgamal.o q_fdivrem.o q_inv.o q_lip_aux.o q_lip_utils.o q_lir_rd_wr.o q_mod.o q_modexp.o q_mulsqr.o q_pka_hw.o q_pke_hw.o q_ppsel.o q_rsa_4k.o q_rsa.o
