# SPDX-License-Identifier: GPL-2.0

dtb-y += 	\
		ethernet-without-gb-phy-overlay.dtb \
		pcf8563-overlay.dtb \
		rx8803-overlay.dtb \
		seconorth-mc3-hdmi-backplane.dtb \
		seconorth-mc3-headless.dtb \
		seconorth-mc3-lq057q3dc12.dtb \
		seconorth-tanaro-atm0700l61ct.dtb \
		seconorth-tanaro-fg0700w0dsswagl1.dtb \
		seconorth-tanaro-fn1010t007b.dtb \
		seconorth-tanaro-g121xcett122e.dtb \
		seconorth-tanaro-headless-no-gb-ethernet.dtb \
		seconorth-tanaro-headless.dtb \
		seconorth-tanaro-qp_070wsvgamlli1d.dtb \
		seconorth-tanaro-scx1001255ggu06.dts \
		seconorth-trizeps8mini-pconxs_v3-atm0700.dtb \
		seconorth-trizeps8mini-pconxs_v3-fn1010t007.dtb \
		seconorth-trizeps8mini_v1-pbb-fn1010t007b.dtb \
		seconorth-trizeps8mini_v2r2-pbb-fn1010t007b.dtb \
		seconorth-trizeps8mini_v2r2-pbb-headless.dtb \
		seconorth-trizeps8mini_v2r2-pconxs_v3-fn1010t007.dtb \
		seconorth-trizeps8plus-dual-espresso.dtb \
		seconorth-trizeps8plus-hdmi-gpu.dtb \
		seconorth-trizeps8plus-pconxs_v3-atm0700.dtb \
		seconorth-trizeps8plus_v1r3-dual-espresso.dtb \
		seconorth-trizeps8plus_v1r3-hdmi-gpu.dtb \
		seconorth-trizeps8plus_v1r3-pbb-fn1010t007b.dtb \
		seconorth-trizeps8plus_v1r3-pbb_v1r1-fn1010t007b.dtb \
		seconorth-trizeps8plus_v1r3_ble-pbb-fn1010t007b.dtb \

always		:= $(dtb-y)
clean-files	:= *.dtb
