/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright 2023 SECO Northern Europe GmbH
 *
 * This file works as abstraction layer between different Trizeps modules.
 * It is based on imx8mm-pinfuncs.h
 *
 */

#ifndef __DTS_TRIZEPS8PLUS_PINFUNC_H
#define __DTS_TRIZEPS8PLUS_PINFUNC_H

#define TRIZEPS8PLUS 1

#define KK_RSRVD_IN	            (1 << 0)
#define KK_RSRVD_OUT            (0 << 0)
#define KK_RSRVD_CHANGEABLE     (1 << 6)
#define KK_RSRVD_OUT_LO		    ((0 << 1) | KK_RSRVD_OUT)
#define KK_RSRVD_OUT_HI		    ((1 << 1) | KK_RSRVD_OUT)
#define KK_RSRVD_REQUEST(_idx)	((1 << 8) | ((_idx) << 16))
#define KK_RSRVD_EXPORT			(1 << 5)					// @+15.05.2017 S&B HL

/*
 * The pin function ID is a tuple of
 * <mux_reg conf_reg input_reg mux_mode input_val>
 */

#define SPIN98_GPIO1_IO00                          MX8MP_IOMUXC_GPIO1_IO00__GPIO1_IO00
#define SPIN98_GPIO                                MX8MP_IOMUXC_GPIO1_IO00__GPIO1_IO00
#define spin98_gpio  &gpio1 0
#define SPIN98_CCM_ENET_PHY_REF_CLK_ROOT           MX8MP_IOMUXC_GPIO1_IO00__CCM_ENET_PHY_REF_CLK_ROOT
#define SPIN98_ISP_FL_TRIG_0                       MX8MP_IOMUXC_GPIO1_IO00__ISP_FL_TRIG_0
#define SPIN98_ANAMIX_REF_CLK_32K                  MX8MP_IOMUXC_GPIO1_IO00__ANAMIX_REF_CLK_32K
#define SPIN98_CCM_EXT_CLK1                        MX8MP_IOMUXC_GPIO1_IO00__CCM_EXT_CLK1
#define SPIN77_GPIO1_IO01                          MX8MP_IOMUXC_GPIO1_IO01__GPIO1_IO01
#define SPIN77_GPIO                                MX8MP_IOMUXC_GPIO1_IO01__GPIO1_IO01
#define spin77_gpio   &gpio1 1
#define SPIN77_PWM1_OUT                            MX8MP_IOMUXC_GPIO1_IO01__PWM1_OUT
#define SPIN77_ISP_SHUTTER_TRIG_0                  MX8MP_IOMUXC_GPIO1_IO01__ISP_SHUTTER_TRIG_0
#define SPIN77_ANAMIX_REF_CLK_24M                  MX8MP_IOMUXC_GPIO1_IO01__ANAMIX_REF_CLK_24M
#define SPIN77_CCM_EXT_CLK2                        MX8MP_IOMUXC_GPIO1_IO01__CCM_EXT_CLK2
#define WDOGRESET_GPIO1_IO02                          MX8MP_IOMUXC_GPIO1_IO02__GPIO1_IO02
#define WDOGRESET_WDOG1_WDOG_B                        MX8MP_IOMUXC_GPIO1_IO02__WDOG1_WDOG_B
#define WDOGRESET_ISP_FLASH_TRIG_0                    MX8MP_IOMUXC_GPIO1_IO02__ISP_FLASH_TRIG_0
#define WDOGRESET_WDOG1_WDOG_ANY                      MX8MP_IOMUXC_GPIO1_IO02__WDOG1_WDOG_ANY
#define WDOGRESET_SJC_DE_B                            MX8MP_IOMUXC_GPIO1_IO02__SJC_DE_B
#define SD1_VSEL_GPIO1_IO03                          MX8MP_IOMUXC_GPIO1_IO03__GPIO1_IO03
#define SD1_VSEL_USDHC1_VSELECT                      MX8MP_IOMUXC_GPIO1_IO03__USDHC1_VSELECT
#define SD1_VSEL_ISP_PRELIGHT_TRIG_0                 MX8MP_IOMUXC_GPIO1_IO03__ISP_PRELIGHT_TRIG_0
#define SD1_VSEL_SDMA1_EXT_EVENT00                   MX8MP_IOMUXC_GPIO1_IO03__SDMA1_EXT_EVENT00
#define SD2_VSEL_GPIO1_IO04                          MX8MP_IOMUXC_GPIO1_IO04__GPIO1_IO04
#define SD2_VSEL_USDHC2_VSELECT                      MX8MP_IOMUXC_GPIO1_IO04__USDHC2_VSELECT
#define SD2_VSEL_ISP_SHUTTER_OPEN_0                  MX8MP_IOMUXC_GPIO1_IO04__ISP_SHUTTER_OPEN_0
#define SD2_VSEL_SDMA1_EXT_EVENT01                   MX8MP_IOMUXC_GPIO1_IO04__SDMA1_EXT_EVENT01
#define SPIN100_GPIO1_IO05                          MX8MP_IOMUXC_GPIO1_IO05__GPIO1_IO05
#define SPIN100_GPIO                                MX8MP_IOMUXC_GPIO1_IO05__GPIO1_IO05
#define DISPLAY_ENABLE                              MX8MP_IOMUXC_GPIO1_IO05__GPIO1_IO05
#define display_enable    &gpio1 5
#define spin100_gpio   &gpio1 5
#define SPIN100_M7_NMI                              MX8MP_IOMUXC_GPIO1_IO05__M7_NMI
#define SPIN100_ISP_FL_TRIG_1                       MX8MP_IOMUXC_GPIO1_IO05__ISP_FL_TRIG_1
#define SPIN100_CCM_PMIC_READY                      MX8MP_IOMUXC_GPIO1_IO05__CCM_PMIC_READY
#define SPIN125_GPIO1_IO06                          MX8MP_IOMUXC_GPIO1_IO06__GPIO1_IO06
#define SPIN125_GPIO                                MX8MP_IOMUXC_GPIO1_IO06__GPIO1_IO06
#define spin125_gpio   &gpio1 6
#define spin125_gpio_pin   6
#define spin125_gpio_parent   &gpio1
#define SPIN125_ENET_QOS_MDC                        MX8MP_IOMUXC_GPIO1_IO06__ENET_QOS_MDC
#define SPIN125_ISP_SHUTTER_TRIG_1                  MX8MP_IOMUXC_GPIO1_IO06__ISP_SHUTTER_TRIG_1
#define SPIN125_USDHC1_CD_B                         MX8MP_IOMUXC_GPIO1_IO06__USDHC1_CD_B
#define SPIN125_CCM_EXT_CLK3                        MX8MP_IOMUXC_GPIO1_IO06__CCM_EXT_CLK3
#define SPIN43_GPIO1_IO07                          MX8MP_IOMUXC_GPIO1_IO07__GPIO1_IO07
#define SPIN43_GPIO                                MX8MP_IOMUXC_GPIO1_IO07__GPIO1_IO07
#define spin43_gpio   &gpio1 7
#define SPIN43_ENET_QOS_MDIO                       MX8MP_IOMUXC_GPIO1_IO07__ENET_QOS_MDIO
#define SPIN43_ISP_FLASH_TRIG_1                    MX8MP_IOMUXC_GPIO1_IO07__ISP_FLASH_TRIG_1
#define SPIN43_USDHC1_WP                           MX8MP_IOMUXC_GPIO1_IO07__USDHC1_WP
#define SPIN43_CCM_EXT_CLK4                        MX8MP_IOMUXC_GPIO1_IO07__CCM_EXT_CLK4
#define SPIN102_GPIO1_IO08                          MX8MP_IOMUXC_GPIO1_IO08__GPIO1_IO08
#define SPIN102_GPIO                                MX8MP_IOMUXC_GPIO1_IO08__GPIO1_IO08
#define spin102_gpio_parent   &gpio1
#define spin102_gpio_pin   8
#define spin102_gpio   &gpio1 8
#define SPIN102_ENET_QOS_1588_EVENT0_IN             MX8MP_IOMUXC_GPIO1_IO08__ENET_QOS_1588_EVENT0_IN
#define SPIN102_PWM1_OUT                            MX8MP_IOMUXC_GPIO1_IO08__PWM1_OUT
#define SPIN102_ISP_PRELIGHT_TRIG_1                 MX8MP_IOMUXC_GPIO1_IO08__ISP_PRELIGHT_TRIG_1
#define SPIN102_ENET_QOS_1588_EVENT0_AUX_IN         MX8MP_IOMUXC_GPIO1_IO08__ENET_QOS_1588_EVENT0_AUX_IN
#define SPIN102_USDHC2_RESET_B                      MX8MP_IOMUXC_GPIO1_IO08__USDHC2_RESET_B
#define ENET_RESET_GPIO1_IO09                          MX8MP_IOMUXC_GPIO1_IO09__GPIO1_IO09
#define ENET_RESET_GPIO                                MX8MP_IOMUXC_GPIO1_IO09__GPIO1_IO09
#define enet_reset_gpio   &gpio1 9
#define ENET_RESET_ENET_QOS_1588_EVENT0_OUT            MX8MP_IOMUXC_GPIO1_IO09__ENET_QOS_1588_EVENT0_OUT
#define ENET_RESET_PWM2_OUT                            MX8MP_IOMUXC_GPIO1_IO09__PWM2_OUT
#define ENET_RESET_ISP_SHUTTER_OPEN_1                  MX8MP_IOMUXC_GPIO1_IO09__ISP_SHUTTER_OPEN_1
#define ENET_RESET_USDHC3_RESET_B                      MX8MP_IOMUXC_GPIO1_IO09__USDHC3_RESET_B
#define ENET_RESET_SDMA2_EXT_EVENT00                   MX8MP_IOMUXC_GPIO1_IO09__SDMA2_EXT_EVENT00
#define MCU_INT_GPIO1_IO10                          MX8MP_IOMUXC_GPIO1_IO10__GPIO1_IO10
#define MCU_INT_GPIO                                MX8MP_IOMUXC_GPIO1_IO10__GPIO1_IO10
#define mcu_int_gpio    &gpio1 10
#define MCU_INT_USB1_ID                             MX8MP_IOMUXC_GPIO1_IO10__USB1_ID
#define MCU_INT_PWM3_OUT                            MX8MP_IOMUXC_GPIO1_IO10__PWM3_OUT
#define SPIN104__GPIO1_IO11                          MX8MP_IOMUXC_GPIO1_IO11__GPIO1_IO11
#define SPIN104__GPIO                                MX8MP_IOMUXC_GPIO1_IO11__GPIO1_IO11
#define SPIN104_GPIO                                 MX8MP_IOMUXC_GPIO1_IO11__GPIO1_IO11
#define spin104_gpio   &gpio1 11
#define SPIN104__USB2_ID                             MX8MP_IOMUXC_GPIO1_IO11__USB2_ID
#define SPIN104__PWM2_OUT                            MX8MP_IOMUXC_GPIO1_IO11__PWM2_OUT
#define SPIN104__USDHC3_VSELECT                      MX8MP_IOMUXC_GPIO1_IO11__USDHC3_VSELECT
#define SPIN104__CCM_PMIC_READY                      MX8MP_IOMUXC_GPIO1_IO11__CCM_PMIC_READY
#define SPIN127_GPIO1_IO12                          MX8MP_IOMUXC_GPIO1_IO12__GPIO1_IO12
#define SPIN127_GPIO                                MX8MP_IOMUXC_GPIO1_IO12__GPIO1_IO12
#define spin127_gpio   &gpio1 12
#define SPIN127_USB1_PWR                            MX8MP_IOMUXC_GPIO1_IO12__USB1_PWR
#define SPIN127_SDMA2_EXT_EVENT01                   MX8MP_IOMUXC_GPIO1_IO12__SDMA2_EXT_EVENT01
#define SPIN133_GPIO1_IO13                          MX8MP_IOMUXC_GPIO1_IO13__GPIO1_IO13
#define SPIN133_GPIO                                MX8MP_IOMUXC_GPIO1_IO13__GPIO1_IO13
#define spin133_gpio   &gpio1 13
#define SPIN133_USB1_OC                             MX8MP_IOMUXC_GPIO1_IO13__USB1_OC
#define SPIN133_PWM2_OUT                            MX8MP_IOMUXC_GPIO1_IO13__PWM2_OUT
#define SPIN129_GPIO1_IO14                          MX8MP_IOMUXC_GPIO1_IO14__GPIO1_IO14
#define SPIN129_GPIO                                MX8MP_IOMUXC_GPIO1_IO14__GPIO1_IO14
#define spin129_gpio   &gpio1 14
#define SPIN129_USB2_PWR                            MX8MP_IOMUXC_GPIO1_IO14__USB2_PWR
#define SPIN129_USDHC3_CD_B                         MX8MP_IOMUXC_GPIO1_IO14__USDHC3_CD_B
#define SPIN129_PWM3_OUT                            MX8MP_IOMUXC_GPIO1_IO14__PWM3_OUT
#define SPIN129_CCM_CLKO1                           MX8MP_IOMUXC_GPIO1_IO14__CCM_CLKO1
#define SPIN131_GPIO1_IO15                          MX8MP_IOMUXC_GPIO1_IO15__GPIO1_IO15
#define SPIN131_GPIO                                MX8MP_IOMUXC_GPIO1_IO15__GPIO1_IO15
#define spin131_gpio   &gpio1 15
#define SPIN131_USB2_OC                             MX8MP_IOMUXC_GPIO1_IO15__USB2_OC
#define SPIN131_USDHC3_WP                           MX8MP_IOMUXC_GPIO1_IO15__USDHC3_WP
#define SPIN131_PWM4_OUT                            MX8MP_IOMUXC_GPIO1_IO15__PWM4_OUT
#define SPIN131_CCM_CLKO2                           MX8MP_IOMUXC_GPIO1_IO15__CCM_CLKO2
#define SPIN59_USDHC2_CD_B                           MX8MP_IOMUXC_SD2_CD_B__USDHC2_CD_B
#define SPIN59_GPIO2_IO12                            MX8MP_IOMUXC_SD2_CD_B__GPIO2_IO12
#define SPIN59_GPIO                                  MX8MP_IOMUXC_SD2_CD_B__GPIO2_IO12
#define spin59_gpio   &gpio2 12
#define SPIN47_USDHC2_CLK                             MX8MP_IOMUXC_SD2_CLK__USDHC2_CLK
#define SPIN47_ECSPI2_SCLK                            MX8MP_IOMUXC_SD2_CLK__ECSPI2_SCLK
#define SPIN47_UART4_DCE_RX                           MX8MP_IOMUXC_SD2_CLK__UART4_DCE_RX
#define SPIN47_UART4_DTE_TX                           MX8MP_IOMUXC_SD2_CLK__UART4_DTE_TX
#define SPIN47_GPIO2_IO13                             MX8MP_IOMUXC_SD2_CLK__GPIO2_IO13
#define SPIN47_GPIO                                   MX8MP_IOMUXC_SD2_CLK__GPIO2_IO13
#define spin47_gpio   &gpio2 13
#define SPIN190_USDHC2_CMD                             MX8MP_IOMUXC_SD2_CMD__USDHC2_CMD
#define SPIN190_ECSPI2_MOSI                            MX8MP_IOMUXC_SD2_CMD__ECSPI2_MOSI
#define SPIN190_UART4_DCE_TX                           MX8MP_IOMUXC_SD2_CMD__UART4_DCE_TX
#define SPIN190_UART4_DTE_RX                           MX8MP_IOMUXC_SD2_CMD__UART4_DTE_RX
#define SPIN190_AUDIOMIX_PDM_CLK                       MX8MP_IOMUXC_SD2_CMD__AUDIOMIX_PDM_CLK
#define SPIN190_GPIO2_IO14                             MX8MP_IOMUXC_SD2_CMD__GPIO2_IO14
#define SPIN190_GPIO                                   MX8MP_IOMUXC_SD2_CMD__GPIO2_IO14
#define spin190_gpio   &gpio2 14
#define SPIN192_USDHC2_DATA0                         MX8MP_IOMUXC_SD2_DATA0__USDHC2_DATA0
#define SPIN192_I2C4_SDA                             MX8MP_IOMUXC_SD2_DATA0__I2C4_SDA
#define SPIN192_UART2_DCE_RX                         MX8MP_IOMUXC_SD2_DATA0__UART2_DCE_RX
#define SPIN192_UART2_DTE_TX                         MX8MP_IOMUXC_SD2_DATA0__UART2_DTE_TX
#define SPIN192_AUDIOMIX_PDM_BIT_STREAM00            MX8MP_IOMUXC_SD2_DATA0__AUDIOMIX_PDM_BIT_STREAM00
#define SPIN192_GPIO2_IO15                           MX8MP_IOMUXC_SD2_DATA0__GPIO2_IO15
#define SPIN192_GPIO                                 MX8MP_IOMUXC_SD2_DATA0__GPIO2_IO15
#define spin192_gpio   &gpio2 15
#define SPIN81_USDHC2_DATA1                         MX8MP_IOMUXC_SD2_DATA1__USDHC2_DATA1
#define SPIN81_I2C4_SCL                             MX8MP_IOMUXC_SD2_DATA1__I2C4_SCL
#define SPIN81_UART2_DCE_TX                         MX8MP_IOMUXC_SD2_DATA1__UART2_DCE_TX
#define SPIN81_UART2_DTE_RX                         MX8MP_IOMUXC_SD2_DATA1__UART2_DTE_RX
#define SPIN81_AUDIOMIX_PDM_BIT_STREAM01            MX8MP_IOMUXC_SD2_DATA1__AUDIOMIX_PDM_BIT_STREAM01
#define SPIN81_GPIO2_IO16                           MX8MP_IOMUXC_SD2_DATA1__GPIO2_IO16
#define SPIN81_GPIO                                 MX8MP_IOMUXC_SD2_DATA1__GPIO2_IO16
#define spin81_gpio   &gpio2 16
#define SPIN85_USDHC2_DATA2                         MX8MP_IOMUXC_SD2_DATA2__USDHC2_DATA2
#define SPIN85_ECSPI2_SS0                           MX8MP_IOMUXC_SD2_DATA2__ECSPI2_SS0
#define SPIN85_AUDIOMIX_SPDIF1_OUT                  MX8MP_IOMUXC_SD2_DATA2__AUDIOMIX_SPDIF1_OUT
#define SPIN85_AUDIOMIX_PDM_BIT_STREAM02            MX8MP_IOMUXC_SD2_DATA2__AUDIOMIX_PDM_BIT_STREAM02
#define SPIN85_GPIO2_IO17                           MX8MP_IOMUXC_SD2_DATA2__GPIO2_IO17
#define SPIN85_GPIO                                 MX8MP_IOMUXC_SD2_DATA2__GPIO2_IO17
#define spin85_gpio   &gpio2 17
#define SPIN86_ECSPI2_SS0                           MX8MP_IOMUXC_ECSPI2_SS0__ECSPI2_SS0
#define SPIN86_GPIO                                 MX8MP_IOMUXC_ECSPI2_SS0__GPIO5_IO13
#define spin86_gpio   &gpio5 13
#define SPIN51_USDHC2_DATA3                         MX8MP_IOMUXC_SD2_DATA3__USDHC2_DATA3
#define SPIN51_ECSPI2_MISO                          MX8MP_IOMUXC_SD2_DATA3__ECSPI2_MISO
#define SPIN51_AUDIOMIX_SPDIF1_IN                   MX8MP_IOMUXC_SD2_DATA3__AUDIOMIX_SPDIF1_IN
#define SPIN51_AUDIOMIX_PDM_BIT_STREAM03            MX8MP_IOMUXC_SD2_DATA3__AUDIOMIX_PDM_BIT_STREAM03
#define SPIN51_GPIO2_IO18                           MX8MP_IOMUXC_SD2_DATA3__GPIO2_IO18
#define SPIN51_GPIO                                 MX8MP_IOMUXC_SD2_DATA3__GPIO2_IO18
#define spin51_gpio   &gpio2 18
#define SPIN106_USDHC2_RESET_B                     MX8MP_IOMUXC_SD2_RESET_B__USDHC2_RESET_B
#define SPIN106_GPIO2_IO19                         MX8MP_IOMUXC_SD2_RESET_B__GPIO2_IO19
#define SPIN106_GPIO                               MX8MP_IOMUXC_SD2_RESET_B__GPIO2_IO19
#define spin106_gpio   &gpio2 19
#define ENET_INT_USDHC2_WP                               MX8MP_IOMUXC_SD2_WP__USDHC2_WP
#define ENET_INT_GPIO2_IO20                              MX8MP_IOMUXC_SD2_WP__GPIO2_IO20
#define ENET_INT_GPIO                                    MX8MP_IOMUXC_SD2_WP__GPIO2_IO20
#define enet_int_gpio   &gpio2 20
#define ENET_INT_CORESIGHT_EVENTI                        MX8MP_IOMUXC_SD2_WP__CORESIGHT_EVENTI
#define SPIN105_NAND_ALE                              MX8MP_IOMUXC_NAND_ALE__NAND_ALE
#define SPIN105_FLEXSPI_A_SCLK                        MX8MP_IOMUXC_NAND_ALE__FLEXSPI_A_SCLK
#define SPIN105_AUDIOMIX_SAI3_TX_BCLK                 MX8MP_IOMUXC_NAND_ALE__AUDIOMIX_SAI3_TX_BCLK
#define SPIN105_ISP_FL_TRIG_0                         MX8MP_IOMUXC_NAND_ALE__ISP_FL_TRIG_0
#define SPIN105_UART3_DCE_RX                          MX8MP_IOMUXC_NAND_ALE__UART3_DCE_RX
#define SPIN105_UART3_DTE_TX                          MX8MP_IOMUXC_NAND_ALE__UART3_DTE_TX
#define SPIN105_GPIO3_IO00                            MX8MP_IOMUXC_NAND_ALE__GPIO3_IO00
#define SPIN105_GPIO                                  MX8MP_IOMUXC_NAND_ALE__GPIO3_IO00
#define spin105_gpio   &gpio3 0
#define SPIN105_CORESIGHT_TRACE_CLK                   MX8MP_IOMUXC_NAND_ALE__CORESIGHT_TRACE_CLK
#define SPIN107_NAND_CE0_B                          MX8MP_IOMUXC_NAND_CE0_B__NAND_CE0_B
#define SPIN107_FLEXSPI_A_SS0_B                     MX8MP_IOMUXC_NAND_CE0_B__FLEXSPI_A_SS0_B
#define SPIN107_AUDIOMIX_SAI3_TX_DATA00             MX8MP_IOMUXC_NAND_CE0_B__AUDIOMIX_SAI3_TX_DATA00
#define SPIN107_ISP_SHUTTER_TRIG_0                  MX8MP_IOMUXC_NAND_CE0_B__ISP_SHUTTER_TRIG_0
#define SPIN107_UART3_DCE_TX                        MX8MP_IOMUXC_NAND_CE0_B__UART3_DCE_TX
#define SPIN107_UART3_DTE_RX                        MX8MP_IOMUXC_NAND_CE0_B__UART3_DTE_RX
#define SPIN107_GPIO3_IO01                          MX8MP_IOMUXC_NAND_CE0_B__GPIO3_IO01
#define SPIN107_GPIO                                MX8MP_IOMUXC_NAND_CE0_B__GPIO3_IO01
#define spin107_gpio   &gpio3 1
#define SPIN107_CORESIGHT_TRACE_CTL                 MX8MP_IOMUXC_NAND_CE0_B__CORESIGHT_TRACE_CTL
#define SPIN154_NAND_CE1_B                          MX8MP_IOMUXC_NAND_CE1_B__NAND_CE1_B
#define SPIN154_FLEXSPI_A_SS1_B                     MX8MP_IOMUXC_NAND_CE1_B__FLEXSPI_A_SS1_B
#define SPIN154_USDHC3_STROBE                       MX8MP_IOMUXC_NAND_CE1_B__USDHC3_STROBE
#define SPIN154_I2C4_SCL                            MX8MP_IOMUXC_NAND_CE1_B__I2C4_SCL
#define SPIN154_GPIO3_IO02                          MX8MP_IOMUXC_NAND_CE1_B__GPIO3_IO02
#define SPIN154_GPIO                                MX8MP_IOMUXC_NAND_CE1_B__GPIO3_IO02
#define spin154_gpio   &gpio3 2
#define SPIN154_CORESIGHT_TRACE00                   MX8MP_IOMUXC_NAND_CE1_B__CORESIGHT_TRACE00
#define SPIN134_NAND_CE2_B                          MX8MP_IOMUXC_NAND_CE2_B__NAND_CE2_B
#define SPIN134_FLEXSPI_B_SS0_B                     MX8MP_IOMUXC_NAND_CE2_B__FLEXSPI_B_SS0_B
#define SPIN134_USDHC3_DATA5                        MX8MP_IOMUXC_NAND_CE2_B__USDHC3_DATA5
#define SPIN134_I2C4_SDA                            MX8MP_IOMUXC_NAND_CE2_B__I2C4_SDA
#define SPIN134_GPIO3_IO03                          MX8MP_IOMUXC_NAND_CE2_B__GPIO3_IO03
#define SPIN134_GPIO                                MX8MP_IOMUXC_NAND_CE2_B__GPIO3_IO03
#define spin134_gpio   &gpio3 3
#define SPIN134_CORESIGHT_TRACE01                   MX8MP_IOMUXC_NAND_CE2_B__CORESIGHT_TRACE01
#define SPIN45_NAND_CE3_B                          MX8MP_IOMUXC_NAND_CE3_B__NAND_CE3_B
#define SPIN45_FLEXSPI_B_SS1_B                     MX8MP_IOMUXC_NAND_CE3_B__FLEXSPI_B_SS1_B
#define SPIN45_USDHC3_DATA6                        MX8MP_IOMUXC_NAND_CE3_B__USDHC3_DATA6
#define SPIN45_I2C3_SDA                            MX8MP_IOMUXC_NAND_CE3_B__I2C3_SDA
#define SPIN45_GPIO3_IO04                          MX8MP_IOMUXC_NAND_CE3_B__GPIO3_IO04
#define SPIN45_GPIO                                MX8MP_IOMUXC_NAND_CE3_B__GPIO3_IO04
#define spin45_gpio   &gpio3 4
#define spin45_gpio_parent   &gpio3
#define spin45_gpio_pin   4
#define SPIN45_CORESIGHT_TRACE02                   MX8MP_IOMUXC_NAND_CE3_B__CORESIGHT_TRACE02
#define TOUCH_INT                                  SPIN45_GPIO
#define touch_int     spin45_gpio
#define touch_int_parent  spin45_gpio_parent
#define touch_int_pin     spin45_gpio_pin

#define SPIN123_NAND_CLE                              MX8MP_IOMUXC_NAND_CLE__NAND_CLE
#define SPIN123_FLEXSPI_B_SCLK                        MX8MP_IOMUXC_NAND_CLE__FLEXSPI_B_SCLK
#define SPIN123_USDHC3_DATA7                          MX8MP_IOMUXC_NAND_CLE__USDHC3_DATA7
#define SPIN123_UART4_DCE_RX                          MX8MP_IOMUXC_NAND_CLE__UART4_DCE_RX
#define SPIN123_UART4_DTE_TX                          MX8MP_IOMUXC_NAND_CLE__UART4_DTE_TX
#define SPIN123_GPIO3_IO05                            MX8MP_IOMUXC_NAND_CLE__GPIO3_IO05
#define SPIN123_GPIO                                  MX8MP_IOMUXC_NAND_CLE__GPIO3_IO05
#define spin123_gpio   &gpio3 5
#define SPIN123_CORESIGHT_TRACE03                     MX8MP_IOMUXC_NAND_CLE__CORESIGHT_TRACE03
#define SPIN111_NAND_DATA00                        MX8MP_IOMUXC_NAND_DATA00__NAND_DATA00
#define SPIN111_FLEXSPI_A_DATA00                   MX8MP_IOMUXC_NAND_DATA00__FLEXSPI_A_DATA00
#define SPIN111_AUDIOMIX_SAI3_RX_DATA00            MX8MP_IOMUXC_NAND_DATA00__AUDIOMIX_SAI3_RX_DATA00
#define SPIN111_ISP_FLASH_TRIG_0                   MX8MP_IOMUXC_NAND_DATA00__ISP_FLASH_TRIG_0
#define SPIN111_UART4_DCE_RX                       MX8MP_IOMUXC_NAND_DATA00__UART4_DCE_RX
#define SPIN111_UART4_DTE_TX                       MX8MP_IOMUXC_NAND_DATA00__UART4_DTE_TX
#define SPIN111_GPIO3_IO06                         MX8MP_IOMUXC_NAND_DATA00__GPIO3_IO06
#define SPIN111_GPIO                               MX8MP_IOMUXC_NAND_DATA00__GPIO3_IO06
#define spin111_gpio   &gpio3  6
#define SPIN111_CORESIGHT_TRACE04                  MX8MP_IOMUXC_NAND_DATA00__CORESIGHT_TRACE04
#define SPIN113_NAND_DATA01                        MX8MP_IOMUXC_NAND_DATA01__NAND_DATA01
#define SPIN113_FLEXSPI_A_DATA01                   MX8MP_IOMUXC_NAND_DATA01__FLEXSPI_A_DATA01
#define SPIN113_AUDIOMIX_SAI3_TX_SYNC              MX8MP_IOMUXC_NAND_DATA01__AUDIOMIX_SAI3_TX_SYNC
#define SPIN113_ISP_PRELIGHT_TRIG_0                MX8MP_IOMUXC_NAND_DATA01__ISP_PRELIGHT_TRIG_0
#define SPIN113_UART4_DCE_TX                       MX8MP_IOMUXC_NAND_DATA01__UART4_DCE_TX
#define SPIN113_UART4_DTE_RX                       MX8MP_IOMUXC_NAND_DATA01__UART4_DTE_RX
#define SPIN113_GPIO3_IO07                         MX8MP_IOMUXC_NAND_DATA01__GPIO3_IO07
#define SPIN113_GPIO                               MX8MP_IOMUXC_NAND_DATA01__GPIO3_IO07
#define spin113_gpio   &gpio3 7
#define SPIN113_CORESIGHT_TRACE05                  MX8MP_IOMUXC_NAND_DATA01__CORESIGHT_TRACE05
#define SPIN117_NAND_DATA02                        MX8MP_IOMUXC_NAND_DATA02__NAND_DATA02
#define SPIN117_FLEXSPI_A_DATA02                   MX8MP_IOMUXC_NAND_DATA02__FLEXSPI_A_DATA02
#define SPIN117_USDHC3_CD_B                        MX8MP_IOMUXC_NAND_DATA02__USDHC3_CD_B
#define SPIN117_UART4_DCE_CTS                      MX8MP_IOMUXC_NAND_DATA02__UART4_DCE_CTS
#define SPIN117_UART4_DTE_RTS                      MX8MP_IOMUXC_NAND_DATA02__UART4_DTE_RTS
#define SPIN117_I2C4_SDA                           MX8MP_IOMUXC_NAND_DATA02__I2C4_SDA
#define SPIN117_GPIO3_IO08                         MX8MP_IOMUXC_NAND_DATA02__GPIO3_IO08
#define SPIN117_GPIO                               MX8MP_IOMUXC_NAND_DATA02__GPIO3_IO08
#define spin117_gpio   &gpio3 8
#define SPIN117_CORESIGHT_TRACE06                  MX8MP_IOMUXC_NAND_DATA02__CORESIGHT_TRACE06
#define SPIN119_NAND_DATA03                        MX8MP_IOMUXC_NAND_DATA03__NAND_DATA03
#define SPIN119_FLEXSPI_A_DATA03                   MX8MP_IOMUXC_NAND_DATA03__FLEXSPI_A_DATA03
#define SPIN119_USDHC3_WP                          MX8MP_IOMUXC_NAND_DATA03__USDHC3_WP
#define SPIN119_UART4_DCE_RTS                      MX8MP_IOMUXC_NAND_DATA03__UART4_DCE_RTS
#define SPIN119_UART4_DTE_CTS                      MX8MP_IOMUXC_NAND_DATA03__UART4_DTE_CTS
#define SPIN119_ISP_FL_TRIG_1                      MX8MP_IOMUXC_NAND_DATA03__ISP_FL_TRIG_1
#define SPIN119_GPIO3_IO09                         MX8MP_IOMUXC_NAND_DATA03__GPIO3_IO09
#define SPIN119_GPIO                               MX8MP_IOMUXC_NAND_DATA03__GPIO3_IO09
#define spin119_gpio   &gpio3 9
#define SPIN119_CORESIGHT_TRACE07                  MX8MP_IOMUXC_NAND_DATA03__CORESIGHT_TRACE07
#define SPIN170_NAND_DATA04                        MX8MP_IOMUXC_NAND_DATA04__NAND_DATA04
#define SPIN170_FLEXSPI_B_DATA00                   MX8MP_IOMUXC_NAND_DATA04__FLEXSPI_B_DATA00
#define SPIN170_USDHC3_DATA0                       MX8MP_IOMUXC_NAND_DATA04__USDHC3_DATA0
#define SPIN170_FLEXSPI_A_DATA04                   MX8MP_IOMUXC_NAND_DATA04__FLEXSPI_A_DATA04
#define SPIN170_ISP_SHUTTER_TRIG_1                 MX8MP_IOMUXC_NAND_DATA04__ISP_SHUTTER_TRIG_1
#define SPIN170_GPIO3_IO10                         MX8MP_IOMUXC_NAND_DATA04__GPIO3_IO10
#define SPIN170_GPIO                               MX8MP_IOMUXC_NAND_DATA04__GPIO3_IO10
#define spin170_gpio   &gpio3 10
#define SPIN170_CORESIGHT_TRACE08                  MX8MP_IOMUXC_NAND_DATA04__CORESIGHT_TRACE08
#define SPIN172_NAND_DATA05                        MX8MP_IOMUXC_NAND_DATA05__NAND_DATA05
#define SPIN172_FLEXSPI_B_DATA01                   MX8MP_IOMUXC_NAND_DATA05__FLEXSPI_B_DATA01
#define SPIN172_USDHC3_DATA1                       MX8MP_IOMUXC_NAND_DATA05__USDHC3_DATA1
#define SPIN172_FLEXSPI_A_DATA05                   MX8MP_IOMUXC_NAND_DATA05__FLEXSPI_A_DATA05
#define SPIN172_ISP_FLASH_TRIG_1                   MX8MP_IOMUXC_NAND_DATA05__ISP_FLASH_TRIG_1
#define SPIN172_GPIO3_IO11                         MX8MP_IOMUXC_NAND_DATA05__GPIO3_IO11
#define SPIN172_GPIO                               MX8MP_IOMUXC_NAND_DATA05__GPIO3_IO11
#define spin172_gpio   &gpio3 11
#define SPIN172_CORESIGHT_TRACE09                  MX8MP_IOMUXC_NAND_DATA05__CORESIGHT_TRACE09
#define SPIN174_NAND_DATA06                        MX8MP_IOMUXC_NAND_DATA06__NAND_DATA06
#define SPIN174_FLEXSPI_B_DATA02                   MX8MP_IOMUXC_NAND_DATA06__FLEXSPI_B_DATA02
#define SPIN174_USDHC3_DATA2                       MX8MP_IOMUXC_NAND_DATA06__USDHC3_DATA2
#define SPIN174_FLEXSPI_A_DATA06                   MX8MP_IOMUXC_NAND_DATA06__FLEXSPI_A_DATA06
#define SPIN174_ISP_PRELIGHT_TRIG_1                MX8MP_IOMUXC_NAND_DATA06__ISP_PRELIGHT_TRIG_1
#define SPIN174_GPIO3_IO12                         MX8MP_IOMUXC_NAND_DATA06__GPIO3_IO12
#define SPIN174_GPIO                               MX8MP_IOMUXC_NAND_DATA06__GPIO3_IO12
#define spin174_gpio   &gpio3 12
#define SPIN174_CORESIGHT_TRACE10                  MX8MP_IOMUXC_NAND_DATA06__CORESIGHT_TRACE10
#define SPIN176_NAND_DATA07                        MX8MP_IOMUXC_NAND_DATA07__NAND_DATA07
#define SPIN176_FLEXSPI_B_DATA03                   MX8MP_IOMUXC_NAND_DATA07__FLEXSPI_B_DATA03
#define SPIN176_USDHC3_DATA3                       MX8MP_IOMUXC_NAND_DATA07__USDHC3_DATA3
#define SPIN176_FLEXSPI_A_DATA07                   MX8MP_IOMUXC_NAND_DATA07__FLEXSPI_A_DATA07
#define SPIN176_ISP_SHUTTER_OPEN_1                 MX8MP_IOMUXC_NAND_DATA07__ISP_SHUTTER_OPEN_1
#define SPIN176_GPIO3_IO13                         MX8MP_IOMUXC_NAND_DATA07__GPIO3_IO13
#define SPIN176_GPIO                               MX8MP_IOMUXC_NAND_DATA07__GPIO3_IO13
#define spin176_gpio   &gpio3 13
#define SPIN176_CORESIGHT_TRACE11                  MX8MP_IOMUXC_NAND_DATA07__CORESIGHT_TRACE11
#define SPIN87_NAND_DQS                              MX8MP_IOMUXC_NAND_DQS__NAND_DQS
#define SPIN87_FLEXSPI_A_DQS                         MX8MP_IOMUXC_NAND_DQS__FLEXSPI_A_DQS
#define SPIN87_AUDIOMIX_SAI3_MCLK                    MX8MP_IOMUXC_NAND_DQS__AUDIOMIX_SAI3_MCLK
#define SPIN87_ISP_SHUTTER_OPEN_0                    MX8MP_IOMUXC_NAND_DQS__ISP_SHUTTER_OPEN_0
#define SPIN87_I2C3_SCL                              MX8MP_IOMUXC_NAND_DQS__I2C3_SCL
#define SPIN87_GPIO3_IO14                            MX8MP_IOMUXC_NAND_DQS__GPIO3_IO14
#define SPIN87_GPIO                                  MX8MP_IOMUXC_NAND_DQS__GPIO3_IO14
#define spin87_gpio   &gpio3 14
#define SPIN87_CORESIGHT_TRACE12                     MX8MP_IOMUXC_NAND_DQS__CORESIGHT_TRACE12
#define SPIN136_NAND_RE_B                            MX8MP_IOMUXC_NAND_RE_B__NAND_RE_B
#define SPIN136_FLEXSPI_B_DQS                        MX8MP_IOMUXC_NAND_RE_B__FLEXSPI_B_DQS
#define SPIN136_USDHC3_DATA4                         MX8MP_IOMUXC_NAND_RE_B__USDHC3_DATA4
#define SPIN136_UART4_DCE_TX                         MX8MP_IOMUXC_NAND_RE_B__UART4_DCE_TX
#define SPIN136_UART4_DTE_RX                         MX8MP_IOMUXC_NAND_RE_B__UART4_DTE_RX
#define SPIN136_GPIO3_IO15                           MX8MP_IOMUXC_NAND_RE_B__GPIO3_IO15
#define SPIN136_GPIO                                 MX8MP_IOMUXC_NAND_RE_B__GPIO3_IO15
#define spin136_gpio   &gpio3 15
#define SPIN136_CORESIGHT_TRACE13                    MX8MP_IOMUXC_NAND_RE_B__CORESIGHT_TRACE13
#define SPIN95_NAND_READY_B                      MX8MP_IOMUXC_NAND_READY_B__NAND_READY_B
#define SPIN95_USDHC3_RESET_B                    MX8MP_IOMUXC_NAND_READY_B__USDHC3_RESET_B
#define SPIN95_I2C3_SCL                          MX8MP_IOMUXC_NAND_READY_B__I2C3_SCL
#define SPIN95_GPIO3_IO16                        MX8MP_IOMUXC_NAND_READY_B__GPIO3_IO16
#define SPIN95_GPIO                              MX8MP_IOMUXC_NAND_READY_B__GPIO3_IO16
#define spin95_gpio   &gpio3 16
#define SPIN95_CORESIGHT_TRACE14                 MX8MP_IOMUXC_NAND_READY_B__CORESIGHT_TRACE14
#define SPIN178_NAND_WE_B                            MX8MP_IOMUXC_NAND_WE_B__NAND_WE_B
#define SPIN178_USDHC3_CLK                           MX8MP_IOMUXC_NAND_WE_B__USDHC3_CLK
#define SPIN178_I2C3_SDA                             MX8MP_IOMUXC_NAND_WE_B__I2C3_SDA
#define SPIN178_GPIO3_IO17                           MX8MP_IOMUXC_NAND_WE_B__GPIO3_IO17
#define SPIN178_GPIO                                 MX8MP_IOMUXC_NAND_WE_B__GPIO3_IO17
#define spin178_gpio   &gpio3 17
#define SPIN178_CORESIGHT_TRACE15                    MX8MP_IOMUXC_NAND_WE_B__CORESIGHT_TRACE15
#define SPIN180_NAND_WP_B                            MX8MP_IOMUXC_NAND_WP_B__NAND_WP_B
#define SPIN180_USDHC3_CMD                           MX8MP_IOMUXC_NAND_WP_B__USDHC3_CMD
#define SPIN180_I2C4_SCL                             MX8MP_IOMUXC_NAND_WP_B__I2C4_SCL
#define SPIN180_GPIO3_IO18                           MX8MP_IOMUXC_NAND_WP_B__GPIO3_IO18
#define SPIN180_GPIO                                 MX8MP_IOMUXC_NAND_WP_B__GPIO3_IO18
#define spin180_gpio   &gpio3 18
#define SPIN180_CORESIGHT_EVENTO                     MX8MP_IOMUXC_NAND_WP_B__CORESIGHT_EVENTO
#define SPIN23_AUDIOMIX_SAI5_RX_SYNC                MX8MP_IOMUXC_SAI5_RXFS__AUDIOMIX_SAI5_RX_SYNC
#define SPIN23_AUDIOMIX_SAI1_TX_DATA00              MX8MP_IOMUXC_SAI5_RXFS__AUDIOMIX_SAI1_TX_DATA00
#define SPIN23_PWM4_OUT                             MX8MP_IOMUXC_SAI5_RXFS__PWM4_OUT
#define SPIN23_I2C6_SCL                             MX8MP_IOMUXC_SAI5_RXFS__I2C6_SCL
#define SPIN23_GPIO3_IO19                           MX8MP_IOMUXC_SAI5_RXFS__GPIO3_IO19
#define SPIN23_GPIO                                 MX8MP_IOMUXC_SAI5_RXFS__GPIO3_IO19
#define spin23_gpio     &gpio3 19
#define SPIN29_AUDIOMIX_SAI5_RX_BCLK                 MX8MP_IOMUXC_SAI5_RXC__AUDIOMIX_SAI5_RX_BCLK
#define SPIN29_AUDIOMIX_SAI1_TX_DATA01               MX8MP_IOMUXC_SAI5_RXC__AUDIOMIX_SAI1_TX_DATA01
#define SPIN29_PWM3_OUT                              MX8MP_IOMUXC_SAI5_RXC__PWM3_OUT
#define SPIN29_I2C6_SDA                              MX8MP_IOMUXC_SAI5_RXC__I2C6_SDA
#define SPIN29_AUDIOMIX_PDM_CLK                      MX8MP_IOMUXC_SAI5_RXC__AUDIOMIX_PDM_CLK
#define SPIN29_GPIO3_IO20                            MX8MP_IOMUXC_SAI5_RXC__GPIO3_IO20
#define SPIN29_GPIO                                  MX8MP_IOMUXC_SAI5_RXC__GPIO3_IO20
#define spin29_gpio   &gpio3 20
#define SPIN55_AUDIOMIX_SAI5_RX_DATA00              MX8MP_IOMUXC_SAI5_RXD0__AUDIOMIX_SAI5_RX_DATA00
#define SPIN55_AUDIOMIX_SAI1_TX_DATA02              MX8MP_IOMUXC_SAI5_RXD0__AUDIOMIX_SAI1_TX_DATA02
#define SPIN55_PWM2_OUT                             MX8MP_IOMUXC_SAI5_RXD0__PWM2_OUT
#define SPIN55_I2C5_SCL                             MX8MP_IOMUXC_SAI5_RXD0__I2C5_SCL
#define SPIN55_AUDIOMIX_PDM_BIT_STREAM00            MX8MP_IOMUXC_SAI5_RXD0__AUDIOMIX_PDM_BIT_STREAM00
#define SPIN55_GPIO3_IO21                           MX8MP_IOMUXC_SAI5_RXD0__GPIO3_IO21
#define SPIN55_GPIO                                 MX8MP_IOMUXC_SAI5_RXD0__GPIO3_IO21
#define spin55_gpio   &gpio3 21
#define SPIN99_AUDIOMIX_SAI5_RX_DATA01              MX8MP_IOMUXC_SAI5_RXD1__AUDIOMIX_SAI5_RX_DATA01
#define SPIN99_AUDIOMIX_SAI1_TX_DATA03              MX8MP_IOMUXC_SAI5_RXD1__AUDIOMIX_SAI1_TX_DATA03
#define SPIN99_AUDIOMIX_SAI1_TX_SYNC                MX8MP_IOMUXC_SAI5_RXD1__AUDIOMIX_SAI1_TX_SYNC
#define SPIN99_AUDIOMIX_SAI5_TX_SYNC                MX8MP_IOMUXC_SAI5_RXD1__AUDIOMIX_SAI5_TX_SYNC
#define SPIN99_AUDIOMIX_PDM_BIT_STREAM01            MX8MP_IOMUXC_SAI5_RXD1__AUDIOMIX_PDM_BIT_STREAM01
#define SPIN99_GPIO3_IO22                           MX8MP_IOMUXC_SAI5_RXD1__GPIO3_IO22
#define SPIN99_GPIO                                 MX8MP_IOMUXC_SAI5_RXD1__GPIO3_IO22
#define spin99_gpio   &gpio3 22
#define SPIN99_CAN1_TX                              MX8MP_IOMUXC_SAI5_RXD1__CAN1_TX
#define SPIN97_AUDIOMIX_SAI5_RX_DATA02              MX8MP_IOMUXC_SAI5_RXD2__AUDIOMIX_SAI5_RX_DATA02
#define SPIN97_AUDIOMIX_SAI1_TX_DATA04              MX8MP_IOMUXC_SAI5_RXD2__AUDIOMIX_SAI1_TX_DATA04
#define SPIN97_AUDIOMIX_SAI1_TX_SYNC                MX8MP_IOMUXC_SAI5_RXD2__AUDIOMIX_SAI1_TX_SYNC
#define SPIN97_AUDIOMIX_SAI5_TX_BCLK                MX8MP_IOMUXC_SAI5_RXD2__AUDIOMIX_SAI5_TX_BCLK
#define SPIN97_AUDIOMIX_PDM_BIT_STREAM02            MX8MP_IOMUXC_SAI5_RXD2__AUDIOMIX_PDM_BIT_STREAM02
#define SPIN97_GPIO3_IO23                           MX8MP_IOMUXC_SAI5_RXD2__GPIO3_IO23
#define SPIN97_GPIO                                 MX8MP_IOMUXC_SAI5_RXD2__GPIO3_IO23
#define spin97_gpio   &gpio3 23
#define SPIN97_CAN1_RX                              MX8MP_IOMUXC_SAI5_RXD2__CAN1_RX
#define SPIN103_AUDIOMIX_SAI5_RX_DATA03              MX8MP_IOMUXC_SAI5_RXD3__AUDIOMIX_SAI5_RX_DATA03
#define SPIN103_AUDIOMIX_SAI1_TX_DATA05              MX8MP_IOMUXC_SAI5_RXD3__AUDIOMIX_SAI1_TX_DATA05
#define SPIN103_AUDIOMIX_SAI1_TX_SYNC                MX8MP_IOMUXC_SAI5_RXD3__AUDIOMIX_SAI1_TX_SYNC
#define SPIN103_AUDIOMIX_SAI5_TX_DATA00              MX8MP_IOMUXC_SAI5_RXD3__AUDIOMIX_SAI5_TX_DATA00
#define SPIN103_AUDIOMIX_PDM_BIT_STREAM03            MX8MP_IOMUXC_SAI5_RXD3__AUDIOMIX_PDM_BIT_STREAM03
#define SPIN103_GPIO3_IO24                           MX8MP_IOMUXC_SAI5_RXD3__GPIO3_IO24
#define SPIN103_GPIO                                 MX8MP_IOMUXC_SAI5_RXD3__GPIO3_IO24
#define spin103_gpio   &gpio3 24
#define SPIN103_CAN2_TX                              MX8MP_IOMUXC_SAI5_RXD3__CAN2_TX
#define SPIN101_AUDIOMIX_SAI5_MCLK                   MX8MP_IOMUXC_SAI5_MCLK__AUDIOMIX_SAI5_MCLK
#define SPIN101_AUDIOMIX_SAI1_TX_BCLK                MX8MP_IOMUXC_SAI5_MCLK__AUDIOMIX_SAI1_TX_BCLK
#define SPIN101_PWM1_OUT                             MX8MP_IOMUXC_SAI5_MCLK__PWM1_OUT
#define SPIN101_I2C5_SDA                             MX8MP_IOMUXC_SAI5_MCLK__I2C5_SDA
#define SPIN101_GPIO3_IO25                           MX8MP_IOMUXC_SAI5_MCLK__GPIO3_IO25
#define SPIN101_GPIO                                 MX8MP_IOMUXC_SAI5_MCLK__GPIO3_IO25
#define spin101_gpio   &gpio3 25
#define SPIN101_CAN2_RX                              MX8MP_IOMUXC_SAI5_MCLK__CAN2_RX
#define SPIN92_AUDIOMIX_SAI1_RX_SYNC                MX8MP_IOMUXC_SAI1_RXFS__AUDIOMIX_SAI1_RX_SYNC
#define SPIN92_ENET1_1588_EVENT0_IN                 MX8MP_IOMUXC_SAI1_RXFS__ENET1_1588_EVENT0_IN
#define SPIN92_GPIO4_IO00                           MX8MP_IOMUXC_SAI1_RXFS__GPIO4_IO00
#define SPIN92_GPIO                                 MX8MP_IOMUXC_SAI1_RXFS__GPIO4_IO00
#define spin92_gpio   &gpio4 0
#define SPIN90_AUDIOMIX_SAI1_RX_BCLK                 MX8MP_IOMUXC_SAI1_RXC__AUDIOMIX_SAI1_RX_BCLK
#define SPIN90_AUDIOMIX_PDM_CLK                      MX8MP_IOMUXC_SAI1_RXC__AUDIOMIX_PDM_CLK
#define SPIN90_ENET1_1588_EVENT0_OUT                 MX8MP_IOMUXC_SAI1_RXC__ENET1_1588_EVENT0_OUT
#define SPIN90_GPIO4_IO01                            MX8MP_IOMUXC_SAI1_RXC__GPIO4_IO01
#define SPIN90_GPIO                                  MX8MP_IOMUXC_SAI1_RXC__GPIO4_IO01
#define spin90_gpio   &gpio4 1
#define SPIN49_AUDIOMIX_SAI1_RX_DATA00              MX8MP_IOMUXC_SAI1_RXD0__AUDIOMIX_SAI1_RX_DATA00
#define SPIN49_AUDIOMIX_SAI1_TX_DATA01              MX8MP_IOMUXC_SAI1_RXD0__AUDIOMIX_SAI1_TX_DATA01
#define SPIN49_AUDIOMIX_PDM_BIT_STREAM00            MX8MP_IOMUXC_SAI1_RXD0__AUDIOMIX_PDM_BIT_STREAM00
#define SPIN49_ENET1_1588_EVENT1_IN                 MX8MP_IOMUXC_SAI1_RXD0__ENET1_1588_EVENT1_IN
#define SPIN49_GPIO4_IO02                           MX8MP_IOMUXC_SAI1_RXD0__GPIO4_IO02
#define SPIN49_GPIO                                 MX8MP_IOMUXC_SAI1_RXD0__GPIO4_IO02
#define spin49_gpio   &gpio4 2
#define SPIN53_AUDIOMIX_SAI1_RX_DATA01              MX8MP_IOMUXC_SAI1_RXD1__AUDIOMIX_SAI1_RX_DATA01
#define SPIN53_AUDIOMIX_PDM_BIT_STREAM01            MX8MP_IOMUXC_SAI1_RXD1__AUDIOMIX_PDM_BIT_STREAM01
#define SPIN53_ENET1_1588_EVENT1_OUT                MX8MP_IOMUXC_SAI1_RXD1__ENET1_1588_EVENT1_OUT
#define SPIN53_GPIO4_IO03                           MX8MP_IOMUXC_SAI1_RXD1__GPIO4_IO03
#define SPIN53_GPIO                                 MX8MP_IOMUXC_SAI1_RXD1__GPIO4_IO03
#define spin53_gpio   &gpio4 3
#define SPIN57_AUDIOMIX_SAI1_RX_DATA02              MX8MP_IOMUXC_SAI1_RXD2__AUDIOMIX_SAI1_RX_DATA02
#define SPIN57_AUDIOMIX_PDM_BIT_STREAM02            MX8MP_IOMUXC_SAI1_RXD2__AUDIOMIX_PDM_BIT_STREAM02
#define SPIN57_ENET1_MDC                            MX8MP_IOMUXC_SAI1_RXD2__ENET1_MDC
#define SPIN57_GPIO4_IO04                           MX8MP_IOMUXC_SAI1_RXD2__GPIO4_IO04
#define SPIN57_GPIO                                 MX8MP_IOMUXC_SAI1_RXD2__GPIO4_IO04
#define spin57_gpio   &gpio4 4
#define SPIN61_AUDIOMIX_SAI1_RX_DATA03              MX8MP_IOMUXC_SAI1_RXD3__AUDIOMIX_SAI1_RX_DATA03
#define SPIN61_AUDIOMIX_PDM_BIT_STREAM03            MX8MP_IOMUXC_SAI1_RXD3__AUDIOMIX_PDM_BIT_STREAM03
#define SPIN61_ENET1_MDIO                           MX8MP_IOMUXC_SAI1_RXD3__ENET1_MDIO
#define SPIN61_GPIO4_IO05                           MX8MP_IOMUXC_SAI1_RXD3__GPIO4_IO05
#define SPIN61_GPIO                                 MX8MP_IOMUXC_SAI1_RXD3__GPIO4_IO05
#define spin61_gpio   &gpio4 5
#define SPIN63_AUDIOMIX_SAI1_RX_DATA04              MX8MP_IOMUXC_SAI1_RXD4__AUDIOMIX_SAI1_RX_DATA04
#define SPIN63_AUDIOMIX_SAI6_TX_BCLK                MX8MP_IOMUXC_SAI1_RXD4__AUDIOMIX_SAI6_TX_BCLK
#define SPIN63_AUDIOMIX_SAI6_RX_BCLK                MX8MP_IOMUXC_SAI1_RXD4__AUDIOMIX_SAI6_RX_BCLK
#define SPIN63_ENET1_RGMII_RD0                      MX8MP_IOMUXC_SAI1_RXD4__ENET1_RGMII_RD0
#define SPIN63_GPIO4_IO06                           MX8MP_IOMUXC_SAI1_RXD4__GPIO4_IO06
#define SPIN63_GPIO                                 MX8MP_IOMUXC_SAI1_RXD4__GPIO4_IO06
#define spin63_gpio   &gpio4 6
#define SPIN65_AUDIOMIX_SAI1_RX_DATA05              MX8MP_IOMUXC_SAI1_RXD5__AUDIOMIX_SAI1_RX_DATA05
#define SPIN65_AUDIOMIX_SAI6_TX_DATA00              MX8MP_IOMUXC_SAI1_RXD5__AUDIOMIX_SAI6_TX_DATA00
#define SPIN65_AUDIOMIX_SAI6_RX_DATA00              MX8MP_IOMUXC_SAI1_RXD5__AUDIOMIX_SAI6_RX_DATA00
#define SPIN65_AUDIOMIX_SAI1_RX_SYNC                MX8MP_IOMUXC_SAI1_RXD5__AUDIOMIX_SAI1_RX_SYNC
#define SPIN65_ENET1_RGMII_RD1                      MX8MP_IOMUXC_SAI1_RXD5__ENET1_RGMII_RD1
#define SPIN65_GPIO4_IO07                           MX8MP_IOMUXC_SAI1_RXD5__GPIO4_IO07
#define SPIN65_GPIO                                 MX8MP_IOMUXC_SAI1_RXD5__GPIO4_IO07
#define spin65_gpio   &gpio4 7
#define SPIN67_AUDIOMIX_SAI1_RX_DATA06              MX8MP_IOMUXC_SAI1_RXD6__AUDIOMIX_SAI1_RX_DATA06
#define SPIN67_AUDIOMIX_SAI6_TX_SYNC                MX8MP_IOMUXC_SAI1_RXD6__AUDIOMIX_SAI6_TX_SYNC
#define SPIN67_AUDIOMIX_SAI6_RX_SYNC                MX8MP_IOMUXC_SAI1_RXD6__AUDIOMIX_SAI6_RX_SYNC
#define SPIN67_ENET1_RGMII_RD2                      MX8MP_IOMUXC_SAI1_RXD6__ENET1_RGMII_RD2
#define SPIN67_GPIO4_IO08                           MX8MP_IOMUXC_SAI1_RXD6__GPIO4_IO08
#define SPIN67_GPIO                                 MX8MP_IOMUXC_SAI1_RXD6__GPIO4_IO08
#define spin67_gpio   &gpio4 8
#define SPIN71_AUDIOMIX_SAI1_RX_DATA07              MX8MP_IOMUXC_SAI1_RXD7__AUDIOMIX_SAI1_RX_DATA07
#define SPIN71_AUDIOMIX_SAI6_MCLK                   MX8MP_IOMUXC_SAI1_RXD7__AUDIOMIX_SAI6_MCLK
#define SPIN71_AUDIOMIX_SAI1_TX_SYNC                MX8MP_IOMUXC_SAI1_RXD7__AUDIOMIX_SAI1_TX_SYNC
#define SPIN71_AUDIOMIX_SAI1_TX_DATA04              MX8MP_IOMUXC_SAI1_RXD7__AUDIOMIX_SAI1_TX_DATA04
#define SPIN71_ENET1_RGMII_RD3                      MX8MP_IOMUXC_SAI1_RXD7__ENET1_RGMII_RD3
#define SPIN71_GPIO4_IO09                           MX8MP_IOMUXC_SAI1_RXD7__GPIO4_IO09
#define SPIN71_GPIO                                 MX8MP_IOMUXC_SAI1_RXD7__GPIO4_IO09
#define spin71_gpio   &gpio4 9
#define SPIN126_AUDIOMIX_SAI1_TX_SYNC                MX8MP_IOMUXC_SAI1_TXFS__AUDIOMIX_SAI1_TX_SYNC
#define SPIN126_ENET1_RGMII_RX_CTL                   MX8MP_IOMUXC_SAI1_TXFS__ENET1_RGMII_RX_CTL
#define SPIN126_GPIO4_IO10                           MX8MP_IOMUXC_SAI1_TXFS__GPIO4_IO10
#define SPIN126_GPIO                                 MX8MP_IOMUXC_SAI1_TXFS__GPIO4_IO10
#define spin126_gpio   &gpio4 10
#define SPIN128_AUDIOMIX_SAI1_TX_BCLK                 MX8MP_IOMUXC_SAI1_TXC__AUDIOMIX_SAI1_TX_BCLK
#define SPIN128_ENET1_RGMII_RXC                       MX8MP_IOMUXC_SAI1_TXC__ENET1_RGMII_RXC
#define SPIN128_GPIO4_IO11                            MX8MP_IOMUXC_SAI1_TXC__GPIO4_IO11
#define SPIN128_GPIO                                  MX8MP_IOMUXC_SAI1_TXC__GPIO4_IO11
#define spin128_gpio   &gpio4 11
#define SPIN110_AUDIOMIX_SAI1_TX_DATA00              MX8MP_IOMUXC_SAI1_TXD0__AUDIOMIX_SAI1_TX_DATA00
#define SPIN110_ENET1_RGMII_TD0                      MX8MP_IOMUXC_SAI1_TXD0__ENET1_RGMII_TD0
#define SPIN110_GPIO4_IO12                           MX8MP_IOMUXC_SAI1_TXD0__GPIO4_IO12
#define SPIN110_GPIO                                 MX8MP_IOMUXC_SAI1_TXD0__GPIO4_IO12
#define spin110_gpio   &gpio4 12
#define SPIN112_AUDIOMIX_SAI1_TX_DATA01              MX8MP_IOMUXC_SAI1_TXD1__AUDIOMIX_SAI1_TX_DATA01
#define SPIN112_ENET1_RGMII_TD1                      MX8MP_IOMUXC_SAI1_TXD1__ENET1_RGMII_TD1
#define SPIN112_GPIO4_IO13                           MX8MP_IOMUXC_SAI1_TXD1__GPIO4_IO13
#define SPIN112_GPIO                                 MX8MP_IOMUXC_SAI1_TXD1__GPIO4_IO13
#define spin112_gpio   &gpio4 13
#define SPIN114_AUDIOMIX_SAI1_TX_DATA02              MX8MP_IOMUXC_SAI1_TXD2__AUDIOMIX_SAI1_TX_DATA02
#define SPIN114_ENET1_RGMII_TD2                      MX8MP_IOMUXC_SAI1_TXD2__ENET1_RGMII_TD2
#define SPIN114_GPIO4_IO14                           MX8MP_IOMUXC_SAI1_TXD2__GPIO4_IO14
#define SPIN114_GPIO                                 MX8MP_IOMUXC_SAI1_TXD2__GPIO4_IO14
#define spin114_gpio   &gpio4 14
#define SPIN116_AUDIOMIX_SAI1_TX_DATA03              MX8MP_IOMUXC_SAI1_TXD3__AUDIOMIX_SAI1_TX_DATA03
#define SPIN116_ENET1_RGMII_TD3                      MX8MP_IOMUXC_SAI1_TXD3__ENET1_RGMII_TD3
#define SPIN116_GPIO4_IO15                           MX8MP_IOMUXC_SAI1_TXD3__GPIO4_IO15
#define SPIN116_GPIO                                 MX8MP_IOMUXC_SAI1_TXD3__GPIO4_IO15
#define spin116_gpio   &gpio4 15
#define SPIN118_AUDIOMIX_SAI1_TX_DATA04              MX8MP_IOMUXC_SAI1_TXD4__AUDIOMIX_SAI1_TX_DATA04
#define SPIN118_AUDIOMIX_SAI6_RX_BCLK                MX8MP_IOMUXC_SAI1_TXD4__AUDIOMIX_SAI6_RX_BCLK
#define SPIN118_AUDIOMIX_SAI6_TX_BCLK                MX8MP_IOMUXC_SAI1_TXD4__AUDIOMIX_SAI6_TX_BCLK
#define SPIN118_ENET1_RGMII_TX_CTL                   MX8MP_IOMUXC_SAI1_TXD4__ENET1_RGMII_TX_CTL
#define SPIN118_GPIO4_IO16                           MX8MP_IOMUXC_SAI1_TXD4__GPIO4_IO16
#define SPIN118_GPIO                                 MX8MP_IOMUXC_SAI1_TXD4__GPIO4_IO16
#define spin118_gpio   &gpio4 16
#define SPIN120_AUDIOMIX_SAI1_TX_DATA05              MX8MP_IOMUXC_SAI1_TXD5__AUDIOMIX_SAI1_TX_DATA05
#define SPIN120_AUDIOMIX_SAI6_RX_DATA00              MX8MP_IOMUXC_SAI1_TXD5__AUDIOMIX_SAI6_RX_DATA00
#define SPIN120_AUDIOMIX_SAI6_TX_DATA00              MX8MP_IOMUXC_SAI1_TXD5__AUDIOMIX_SAI6_TX_DATA00
#define SPIN120_ENET1_RGMII_TXC                      MX8MP_IOMUXC_SAI1_TXD5__ENET1_RGMII_TXC
#define SPIN120_GPIO4_IO17                           MX8MP_IOMUXC_SAI1_TXD5__GPIO4_IO17
#define SPIN120_GPIO                                 MX8MP_IOMUXC_SAI1_TXD5__GPIO4_IO17
#define spin120_gpio   &gpio4 17
#define SPIN122_AUDIOMIX_SAI1_TX_DATA06              MX8MP_IOMUXC_SAI1_TXD6__AUDIOMIX_SAI1_TX_DATA06
#define SPIN122_AUDIOMIX_SAI6_RX_SYNC                MX8MP_IOMUXC_SAI1_TXD6__AUDIOMIX_SAI6_RX_SYNC
#define SPIN122_AUDIOMIX_SAI6_TX_SYNC                MX8MP_IOMUXC_SAI1_TXD6__AUDIOMIX_SAI6_TX_SYNC
#define SPIN122_ENET1_RX_ER                          MX8MP_IOMUXC_SAI1_TXD6__ENET1_RX_ER
#define SPIN122_GPIO4_IO18                           MX8MP_IOMUXC_SAI1_TXD6__GPIO4_IO18
#define SPIN122_GPIO                                 MX8MP_IOMUXC_SAI1_TXD6__GPIO4_IO18
#define spin122_gpio   &gpio4 18
#define SPIN124_AUDIOMIX_SAI1_TX_DATA07              MX8MP_IOMUXC_SAI1_TXD7__AUDIOMIX_SAI1_TX_DATA07
#define SPIN124_AUDIOMIX_SAI6_MCLK                   MX8MP_IOMUXC_SAI1_TXD7__AUDIOMIX_SAI6_MCLK
#define SPIN124_AUDIOMIX_PDM_CLK                     MX8MP_IOMUXC_SAI1_TXD7__AUDIOMIX_PDM_CLK
#define SPIN124_ENET1_TX_ER                          MX8MP_IOMUXC_SAI1_TXD7__ENET1_TX_ER
#define SPIN124_GPIO4_IO19                           MX8MP_IOMUXC_SAI1_TXD7__GPIO4_IO19
#define SPIN124_GPIO                                 MX8MP_IOMUXC_SAI1_TXD7__GPIO4_IO19
#define spin124_gpio   &gpio4 19
#define SPIN88_AUDIOMIX_SAI1_MCLK                   MX8MP_IOMUXC_SAI1_MCLK__AUDIOMIX_SAI1_MCLK
#define SPIN88_AUDIOMIX_SAI1_TX_BCLK                MX8MP_IOMUXC_SAI1_MCLK__AUDIOMIX_SAI1_TX_BCLK
#define SPIN88_ENET1_TX_CLK                         MX8MP_IOMUXC_SAI1_MCLK__ENET1_TX_CLK
#define SPIN88_GPIO4_IO20                           MX8MP_IOMUXC_SAI1_MCLK__GPIO4_IO20
#define SPIN88_GPIO                                 MX8MP_IOMUXC_SAI1_MCLK__GPIO4_IO20
#define spin88_gpio   &gpio4 20
#define SPIN31_AUDIOMIX_SAI2_RX_SYNC                MX8MP_IOMUXC_SAI2_RXFS__AUDIOMIX_SAI2_RX_SYNC
#define SPIN31_AUDIOMIX_SAI5_TX_SYNC                MX8MP_IOMUXC_SAI2_RXFS__AUDIOMIX_SAI5_TX_SYNC
#define SPIN31_AUDIOMIX_SAI5_TX_DATA01              MX8MP_IOMUXC_SAI2_RXFS__AUDIOMIX_SAI5_TX_DATA01
#define SPIN31_AUDIOMIX_SAI2_RX_DATA01              MX8MP_IOMUXC_SAI2_RXFS__AUDIOMIX_SAI2_RX_DATA01
#define SPIN31_UART1_DCE_TX                         MX8MP_IOMUXC_SAI2_RXFS__UART1_DCE_TX
#define SPIN31_UART1_DTE_RX                         MX8MP_IOMUXC_SAI2_RXFS__UART1_DTE_RX
#define SPIN31_GPIO4_IO21                           MX8MP_IOMUXC_SAI2_RXFS__GPIO4_IO21
#define SPIN31_GPIO                                 MX8MP_IOMUXC_SAI2_RXFS__GPIO4_IO21
#define spin31_gpio   &gpio4 21
#define SPIN31_AUDIOMIX_PDM_BIT_STREAM02            MX8MP_IOMUXC_SAI2_RXFS__AUDIOMIX_PDM_BIT_STREAM02
#define SPIN37_AUDIOMIX_SAI2_RX_BCLK                 MX8MP_IOMUXC_SAI2_RXC__AUDIOMIX_SAI2_RX_BCLK
#define SPIN37_AUDIOMIX_SAI5_TX_BCLK                 MX8MP_IOMUXC_SAI2_RXC__AUDIOMIX_SAI5_TX_BCLK
#define SPIN37_CAN1_TX                               MX8MP_IOMUXC_SAI2_RXC__CAN1_TX
#define SPIN37_UART1_DCE_RX                          MX8MP_IOMUXC_SAI2_RXC__UART1_DCE_RX
#define SPIN37_UART1_DTE_TX                          MX8MP_IOMUXC_SAI2_RXC__UART1_DTE_TX
#define SPIN37_GPIO4_IO22                            MX8MP_IOMUXC_SAI2_RXC__GPIO4_IO22
#define SPIN37_GPIO                                  MX8MP_IOMUXC_SAI2_RXC__GPIO4_IO22
#define spin37_gpio   &gpio4 22
#define SPIN37_AUDIOMIX_PDM_BIT_STREAM01             MX8MP_IOMUXC_SAI2_RXC__AUDIOMIX_PDM_BIT_STREAM01
#define SAI2_RXD_AUDIOMIX_SAI2_RX_DATA00              MX8MP_IOMUXC_SAI2_RXD0__AUDIOMIX_SAI2_RX_DATA00
#define SAI2_RXD_AUDIOMIX_SAI5_TX_DATA00              MX8MP_IOMUXC_SAI2_RXD0__AUDIOMIX_SAI5_TX_DATA00
#define SAI2_RXD_ENET_QOS_1588_EVENT2_OUT             MX8MP_IOMUXC_SAI2_RXD0__ENET_QOS_1588_EVENT2_OUT
#define SAI2_RXD_AUDIOMIX_SAI2_TX_DATA01              MX8MP_IOMUXC_SAI2_RXD0__AUDIOMIX_SAI2_TX_DATA01
#define SAI2_RXD_UART1_DCE_RTS                        MX8MP_IOMUXC_SAI2_RXD0__UART1_DCE_RTS
#define SAI2_RXD_UART1_DTE_CTS                        MX8MP_IOMUXC_SAI2_RXD0__UART1_DTE_CTS
#define SAI2_RXD_GPIO4_IO23                           MX8MP_IOMUXC_SAI2_RXD0__GPIO4_IO23
#define SAI2_RXD_GPIO                                 MX8MP_IOMUXC_SAI2_RXD0__GPIO4_IO23
#define sai2_rxd_gpio   &gpio4 23
#define SAI2_RXD_AUDIOMIX_PDM_BIT_STREAM03            MX8MP_IOMUXC_SAI2_RXD0__AUDIOMIX_PDM_BIT_STREAM03
#define SAI2_TXFS_AUDIOMIX_SAI2_TX_SYNC                MX8MP_IOMUXC_SAI2_TXFS__AUDIOMIX_SAI2_TX_SYNC
#define SAI2_TXFS_AUDIOMIX_SAI5_TX_DATA01              MX8MP_IOMUXC_SAI2_TXFS__AUDIOMIX_SAI5_TX_DATA01
#define SAI2_TXFS_ENET_QOS_1588_EVENT3_OUT             MX8MP_IOMUXC_SAI2_TXFS__ENET_QOS_1588_EVENT3_OUT
#define SAI2_TXFS_AUDIOMIX_SAI2_TX_DATA01              MX8MP_IOMUXC_SAI2_TXFS__AUDIOMIX_SAI2_TX_DATA01
#define SAI2_TXFS_UART1_DCE_CTS                        MX8MP_IOMUXC_SAI2_TXFS__UART1_DCE_CTS
#define SAI2_TXFS_UART1_DTE_RTS                        MX8MP_IOMUXC_SAI2_TXFS__UART1_DTE_RTS
#define SAI2_TXFS_GPIO4_IO24                           MX8MP_IOMUXC_SAI2_TXFS__GPIO4_IO24
#define SAI2_TXFS_GPIO                                 MX8MP_IOMUXC_SAI2_TXFS__GPIO4_IO24
#define sai2_txfs_gpio   &gpio4 24
#define SAI2_TXFS_AUDIOMIX_PDM_BIT_STREAM02            MX8MP_IOMUXC_SAI2_TXFS__AUDIOMIX_PDM_BIT_STREAM02
#define SAI2_TXC_AUDIOMIX_SAI2_TX_BCLK                 MX8MP_IOMUXC_SAI2_TXC__AUDIOMIX_SAI2_TX_BCLK
#define SAI2_TXC_AUDIOMIX_SAI5_TX_DATA02               MX8MP_IOMUXC_SAI2_TXC__AUDIOMIX_SAI5_TX_DATA02
#define SAI2_TXC_CAN1_RX                               MX8MP_IOMUXC_SAI2_TXC__CAN1_RX
#define SAI2_TXC_GPIO4_IO25                            MX8MP_IOMUXC_SAI2_TXC__GPIO4_IO25
#define SAI2_TXC_GPIO                                  MX8MP_IOMUXC_SAI2_TXC__GPIO4_IO25
#define sai2_txc_gpio   &gpio4 25
#define SAI2_TXC_AUDIOMIX_PDM_BIT_STREAM01             MX8MP_IOMUXC_SAI2_TXC__AUDIOMIX_PDM_BIT_STREAM01
#define SAI2_TXD_AUDIOMIX_SAI2_TX_DATA00              MX8MP_IOMUXC_SAI2_TXD0__AUDIOMIX_SAI2_TX_DATA00
#define SAI2_TXD_AUDIOMIX_SAI5_TX_DATA03              MX8MP_IOMUXC_SAI2_TXD0__AUDIOMIX_SAI5_TX_DATA03
#define SAI2_TXD_ENET_QOS_1588_EVENT2_IN              MX8MP_IOMUXC_SAI2_TXD0__ENET_QOS_1588_EVENT2_IN
#define SAI2_TXD_CAN2_TX                              MX8MP_IOMUXC_SAI2_TXD0__CAN2_TX
#define SAI2_TXD_ENET_QOS_1588_EVENT2_AUX_IN          MX8MP_IOMUXC_SAI2_TXD0__ENET_QOS_1588_EVENT2_AUX_IN
#define SAI2_TXD_GPIO4_IO26                           MX8MP_IOMUXC_SAI2_TXD0__GPIO4_IO26
#define SAI2_TXD_GPIO                                 MX8MP_IOMUXC_SAI2_TXD0__GPIO4_IO26
#define sai2_txd_gpio   &gpio4 26
#define SAI2_MCLK_AUDIOMIX_SAI2_MCLK                   MX8MP_IOMUXC_SAI2_MCLK__AUDIOMIX_SAI2_MCLK
#define SAI2_MCLK_AUDIOMIX_SAI5_MCLK                   MX8MP_IOMUXC_SAI2_MCLK__AUDIOMIX_SAI5_MCLK
#define SAI2_MCLK_ENET_QOS_1588_EVENT3_IN              MX8MP_IOMUXC_SAI2_MCLK__ENET_QOS_1588_EVENT3_IN
#define SAI2_MCLK_CAN2_RX                              MX8MP_IOMUXC_SAI2_MCLK__CAN2_RX
#define SAI2_MCLK_ENET_QOS_1588_EVENT3_AUX_IN          MX8MP_IOMUXC_SAI2_MCLK__ENET_QOS_1588_EVENT3_AUX_IN
#define SAI2_MCLK_GPIO4_IO27                           MX8MP_IOMUXC_SAI2_MCLK__GPIO4_IO27
#define SAI2_MCLK_GPIO                                 MX8MP_IOMUXC_SAI2_MCLK__GPIO4_IO27
#define sai2_mclk_gpio   &gpio4 27
#define SAI2_MCLK_AUDIOMIX_SAI3_MCLK                   MX8MP_IOMUXC_SAI2_MCLK__AUDIOMIX_SAI3_MCLK
#define SPIN188_AUDIOMIX_SAI3_RX_SYNC                MX8MP_IOMUXC_SAI3_RXFS__AUDIOMIX_SAI3_RX_SYNC
#define SPIN188_AUDIOMIX_SAI2_RX_DATA01              MX8MP_IOMUXC_SAI3_RXFS__AUDIOMIX_SAI2_RX_DATA01
#define SPIN188_AUDIOMIX_SAI5_RX_SYNC                MX8MP_IOMUXC_SAI3_RXFS__AUDIOMIX_SAI5_RX_SYNC
#define SPIN188_AUDIOMIX_SAI3_RX_DATA01              MX8MP_IOMUXC_SAI3_RXFS__AUDIOMIX_SAI3_RX_DATA01
#define SPIN188_AUDIOMIX_SPDIF1_IN                   MX8MP_IOMUXC_SAI3_RXFS__AUDIOMIX_SPDIF1_IN
#define SPIN188_GPIO4_IO28                           MX8MP_IOMUXC_SAI3_RXFS__GPIO4_IO28
#define SPIN188_GPIO                                 MX8MP_IOMUXC_SAI3_RXFS__GPIO4_IO28
#define spin188_gpio   &gpio4 28
#define SPIN188_AUDIOMIX_PDM_BIT_STREAM00            MX8MP_IOMUXC_SAI3_RXFS__AUDIOMIX_PDM_BIT_STREAM00
#define SPIN186_AUDIOMIX_SAI3_RX_BCLK                 MX8MP_IOMUXC_SAI3_RXC__AUDIOMIX_SAI3_RX_BCLK
#define SPIN186_AUDIOMIX_SAI2_RX_DATA02               MX8MP_IOMUXC_SAI3_RXC__AUDIOMIX_SAI2_RX_DATA02
#define SPIN186_AUDIOMIX_SAI5_RX_BCLK                 MX8MP_IOMUXC_SAI3_RXC__AUDIOMIX_SAI5_RX_BCLK
#define SPIN186_GPT1_CLK                              MX8MP_IOMUXC_SAI3_RXC__GPT1_CLK
#define SPIN186_UART2_DCE_CTS                         MX8MP_IOMUXC_SAI3_RXC__UART2_DCE_CTS
#define SPIN186_UART2_DTE_RTS                         MX8MP_IOMUXC_SAI3_RXC__UART2_DTE_RTS
#define SPIN186_GPIO4_IO29                            MX8MP_IOMUXC_SAI3_RXC__GPIO4_IO29
#define SPIN186_GPIO                                  MX8MP_IOMUXC_SAI3_RXC__GPIO4_IO29
#define spin186_gpio   &gpio4 29
#define SPIN186_AUDIOMIX_PDM_CLK                      MX8MP_IOMUXC_SAI3_RXC__AUDIOMIX_PDM_CLK
#define SPIN184_AUDIOMIX_SAI3_RX_DATA00               MX8MP_IOMUXC_SAI3_RXD__AUDIOMIX_SAI3_RX_DATA00
#define SPIN184_AUDIOMIX_SAI2_RX_DATA03               MX8MP_IOMUXC_SAI3_RXD__AUDIOMIX_SAI2_RX_DATA03
#define SPIN184_AUDIOMIX_SAI5_RX_DATA00               MX8MP_IOMUXC_SAI3_RXD__AUDIOMIX_SAI5_RX_DATA00
#define SPIN184_UART2_DCE_RTS                         MX8MP_IOMUXC_SAI3_RXD__UART2_DCE_RTS
#define SPIN184_UART2_DTE_CTS                         MX8MP_IOMUXC_SAI3_RXD__UART2_DTE_CTS
#define SPIN184_GPIO4_IO30                            MX8MP_IOMUXC_SAI3_RXD__GPIO4_IO30
#define SPIN184_GPIO                                  MX8MP_IOMUXC_SAI3_RXD__GPIO4_IO30
#define spin184_gpio   &gpio4 30
#define SPIN184_AUDIOMIX_PDM_BIT_STREAM01             MX8MP_IOMUXC_SAI3_RXD__AUDIOMIX_PDM_BIT_STREAM01
#define SPIN73_AUDIOMIX_SAI3_TX_SYNC                MX8MP_IOMUXC_SAI3_TXFS__AUDIOMIX_SAI3_TX_SYNC
#define SPIN73_AUDIOMIX_SAI2_TX_DATA01              MX8MP_IOMUXC_SAI3_TXFS__AUDIOMIX_SAI2_TX_DATA01
#define SPIN73_AUDIOMIX_SAI5_RX_DATA01              MX8MP_IOMUXC_SAI3_TXFS__AUDIOMIX_SAI5_RX_DATA01
#define SPIN73_AUDIOMIX_SAI3_TX_DATA01              MX8MP_IOMUXC_SAI3_TXFS__AUDIOMIX_SAI3_TX_DATA01
#define SPIN73_UART2_DCE_RX                         MX8MP_IOMUXC_SAI3_TXFS__UART2_DCE_RX
#define SPIN73_UART2_DTE_TX                         MX8MP_IOMUXC_SAI3_TXFS__UART2_DTE_TX
#define SPIN73_GPIO4_IO31                           MX8MP_IOMUXC_SAI3_TXFS__GPIO4_IO31
#define SPIN73_GPIO                                 MX8MP_IOMUXC_SAI3_TXFS__GPIO4_IO31
#define spin73_gpio   &gpio4 31
#define SPIN73_AUDIOMIX_PDM_BIT_STREAM03            MX8MP_IOMUXC_SAI3_TXFS__AUDIOMIX_PDM_BIT_STREAM03
#define SPIN79_AUDIOMIX_SAI3_TX_BCLK                 MX8MP_IOMUXC_SAI3_TXC__AUDIOMIX_SAI3_TX_BCLK
#define SPIN79_AUDIOMIX_SAI2_TX_DATA02               MX8MP_IOMUXC_SAI3_TXC__AUDIOMIX_SAI2_TX_DATA02
#define SPIN79_AUDIOMIX_SAI5_RX_DATA02               MX8MP_IOMUXC_SAI3_TXC__AUDIOMIX_SAI5_RX_DATA02
#define SPIN79_GPT1_CAPTURE1                         MX8MP_IOMUXC_SAI3_TXC__GPT1_CAPTURE1
#define SPIN79_UART2_DCE_TX                          MX8MP_IOMUXC_SAI3_TXC__UART2_DCE_TX
#define SPIN79_UART2_DTE_RX                          MX8MP_IOMUXC_SAI3_TXC__UART2_DTE_RX
#define SPIN79_GPIO5_IO00                            MX8MP_IOMUXC_SAI3_TXC__GPIO5_IO00
#define SPIN79_GPIO                                  MX8MP_IOMUXC_SAI3_TXC__GPIO5_IO00
#define spin79_gpio   &gpio5 0
#define SPIN79_AUDIOMIX_PDM_BIT_STREAM02             MX8MP_IOMUXC_SAI3_TXC__AUDIOMIX_PDM_BIT_STREAM02
#define SPIN146_AUDIOMIX_SAI3_TX_DATA00               MX8MP_IOMUXC_SAI3_TXD__AUDIOMIX_SAI3_TX_DATA00
#define SPIN146_AUDIOMIX_SAI2_TX_DATA03               MX8MP_IOMUXC_SAI3_TXD__AUDIOMIX_SAI2_TX_DATA03
#define SPIN146_AUDIOMIX_SAI5_RX_DATA03               MX8MP_IOMUXC_SAI3_TXD__AUDIOMIX_SAI5_RX_DATA03
#define SPIN146_GPT1_CAPTURE2                         MX8MP_IOMUXC_SAI3_TXD__GPT1_CAPTURE2
#define SPIN146_AUDIOMIX_SPDIF1_EXT_CLK               MX8MP_IOMUXC_SAI3_TXD__AUDIOMIX_SPDIF1_EXT_CLK
#define SPIN146_GPIO5_IO01                            MX8MP_IOMUXC_SAI3_TXD__GPIO5_IO01
#define SPIN146_GPIO                                  MX8MP_IOMUXC_SAI3_TXD__GPIO5_IO01
#define spin146_gpio   &gpio5 1
#define SPIN69_AUDIOMIX_SAI3_MCLK                   MX8MP_IOMUXC_SAI3_MCLK__AUDIOMIX_SAI3_MCLK
#define SPIN69_PWM4_OUT                             MX8MP_IOMUXC_SAI3_MCLK__PWM4_OUT
#define SPIN69_AUDIOMIX_SAI5_MCLK                   MX8MP_IOMUXC_SAI3_MCLK__AUDIOMIX_SAI5_MCLK
#define SPIN69_AUDIOMIX_SPDIF1_OUT                  MX8MP_IOMUXC_SAI3_MCLK__AUDIOMIX_SPDIF1_OUT
#define SPIN69_GPIO5_IO02                           MX8MP_IOMUXC_SAI3_MCLK__GPIO5_IO02
#define SPIN69_GPIO                                 MX8MP_IOMUXC_SAI3_MCLK__GPIO5_IO02
#define spin69_gpio   &gpio5 2
#define SPIN69_AUDIOMIX_SPDIF1_IN                   MX8MP_IOMUXC_SAI3_MCLK__AUDIOMIX_SPDIF1_IN
#define SPIN161_AUDIOMIX_SPDIF1_OUT                   MX8MP_IOMUXC_SPDIF_TX__AUDIOMIX_SPDIF1_OUT
#define SPIN161_PWM3_OUT                              MX8MP_IOMUXC_SPDIF_TX__PWM3_OUT
#define SPIN161_I2C5_SCL                              MX8MP_IOMUXC_SPDIF_TX__I2C5_SCL
#define SPIN161_GPT1_COMPARE1                         MX8MP_IOMUXC_SPDIF_TX__GPT1_COMPARE1
#define SPIN161_CAN1_TX                               MX8MP_IOMUXC_SPDIF_TX__CAN1_TX
#define SPIN161_GPIO5_IO03                            MX8MP_IOMUXC_SPDIF_TX__GPIO5_IO03
#define SPIN161_GPIO                                  MX8MP_IOMUXC_SPDIF_TX__GPIO5_IO03
#define spin161_gpio   &gpio5 3
#define SPIN159_AUDIOMIX_SPDIF1_IN                    MX8MP_IOMUXC_SPDIF_RX__AUDIOMIX_SPDIF1_IN
#define SPIN159_PWM2_OUT                              MX8MP_IOMUXC_SPDIF_RX__PWM2_OUT
#define SPIN159_I2C5_SDA                              MX8MP_IOMUXC_SPDIF_RX__I2C5_SDA
#define SPIN159_GPT1_COMPARE2                         MX8MP_IOMUXC_SPDIF_RX__GPT1_COMPARE2
#define SPIN159_CAN1_RX                               MX8MP_IOMUXC_SPDIF_RX__CAN1_RX
#define SPIN159_GPIO5_IO04                            MX8MP_IOMUXC_SPDIF_RX__GPIO5_IO04
#define SPIN159_GPIO                                  MX8MP_IOMUXC_SPDIF_RX__GPIO5_IO04
#define spin159_gpio   &gpio5 4
#define SPIN163_GPT1_COMPARE3                    MX8MP_IOMUXC_SPDIF_EXT_CLK__GPT1_COMPARE3
#define SPIN163_GPIO5_IO05                       MX8MP_IOMUXC_SPDIF_EXT_CLK__GPIO5_IO05
#define SPIN163_GPIO                             MX8MP_IOMUXC_SPDIF_EXT_CLK__GPIO5_IO05
#define spin163_gpio   &gpio5 5 
#define SPIN163_AUDIOMIX_SPDIF1_EXT_CLK          MX8MP_IOMUXC_SPDIF_EXT_CLK__AUDIOMIX_SPDIF1_EXT_CLK
#define SPIN163_PWM1_OUT                         MX8MP_IOMUXC_SPDIF_EXT_CLK__PWM1_OUT
#define SPIN19_ECSPI1_SCLK                        MX8MP_IOMUXC_ECSPI1_SCLK__ECSPI1_SCLK
#define SPIN19_UART3_DCE_RX                       MX8MP_IOMUXC_ECSPI1_SCLK__UART3_DCE_RX
#define SPIN19_UART3_DTE_TX                       MX8MP_IOMUXC_ECSPI1_SCLK__UART3_DTE_TX
#define SPIN19_I2C1_SCL                           MX8MP_IOMUXC_ECSPI1_SCLK__I2C1_SCL
#define SPIN19_AUDIOMIX_SAI7_RX_SYNC              MX8MP_IOMUXC_ECSPI1_SCLK__AUDIOMIX_SAI7_RX_SYNC
#define SPIN19_GPIO5_IO06                         MX8MP_IOMUXC_ECSPI1_SCLK__GPIO5_IO06
#define SPIN19_GPIO                               MX8MP_IOMUXC_ECSPI1_SCLK__GPIO5_IO06
#define spin19_gpio   &gpio5 6
#define SPIN21_ECSPI1_MOSI                        MX8MP_IOMUXC_ECSPI1_MOSI__ECSPI1_MOSI
#define SPIN21_UART3_DCE_TX                       MX8MP_IOMUXC_ECSPI1_MOSI__UART3_DCE_TX
#define SPIN21_UART3_DTE_RX                       MX8MP_IOMUXC_ECSPI1_MOSI__UART3_DTE_RX
#define SPIN21_I2C1_SDA                           MX8MP_IOMUXC_ECSPI1_MOSI__I2C1_SDA
#define SPIN21_AUDIOMIX_SAI7_RX_BCLK              MX8MP_IOMUXC_ECSPI1_MOSI__AUDIOMIX_SAI7_RX_BCLK
#define SPIN21_GPIO5_IO07                         MX8MP_IOMUXC_ECSPI1_MOSI__GPIO5_IO07
#define SPIN21_GPIO                               MX8MP_IOMUXC_ECSPI1_MOSI__GPIO5_IO07
#define spin21_gpio     &gpio5 7
#define SPIN22_ECSPI1_MISO                        MX8MP_IOMUXC_ECSPI1_MISO__ECSPI1_MISO
#define SPIN22_UART3_DCE_CTS                      MX8MP_IOMUXC_ECSPI1_MISO__UART3_DCE_CTS
#define SPIN22_UART3_DTE_RTS                      MX8MP_IOMUXC_ECSPI1_MISO__UART3_DTE_RTS
#define SPIN22_I2C2_SCL                           MX8MP_IOMUXC_ECSPI1_MISO__I2C2_SCL
#define SPIN22_AUDIOMIX_SAI7_RX_DATA00            MX8MP_IOMUXC_ECSPI1_MISO__AUDIOMIX_SAI7_RX_DATA00
#define SPIN22_GPIO5_IO08                         MX8MP_IOMUXC_ECSPI1_MISO__GPIO5_IO08
#define SPIN22_GPIO                               MX8MP_IOMUXC_ECSPI1_MISO__GPIO5_IO08
#define spin22_gpio   &gpio5 8
#define SPIN24_ECSPI1_SS0                          MX8MP_IOMUXC_ECSPI1_SS0__ECSPI1_SS0
#define SPIN24_UART3_DCE_RTS                       MX8MP_IOMUXC_ECSPI1_SS0__UART3_DCE_RTS
#define SPIN24_UART3_DTE_CTS                       MX8MP_IOMUXC_ECSPI1_SS0__UART3_DTE_CTS
#define SPIN24_I2C2_SDA                            MX8MP_IOMUXC_ECSPI1_SS0__I2C2_SDA
#define SPIN24_AUDIOMIX_SAI7_TX_SYNC               MX8MP_IOMUXC_ECSPI1_SS0__AUDIOMIX_SAI7_TX_SYNC
#define SPIN24_GPIO5_IO09                          MX8MP_IOMUXC_ECSPI1_SS0__GPIO5_IO09
#define SPIN24_GPIO                                MX8MP_IOMUXC_ECSPI1_SS0__GPIO5_IO09
#define spin24_gpio   &gpio5 9
#define SPI2_SCLK_ECSPI2_SCLK                        MX8MP_IOMUXC_ECSPI2_SCLK__ECSPI2_SCLK
#define SPI2_SCLK_UART4_DCE_RX                       MX8MP_IOMUXC_ECSPI2_SCLK__UART4_DCE_RX
#define SPI2_SCLK_UART4_DTE_TX                       MX8MP_IOMUXC_ECSPI2_SCLK__UART4_DTE_TX
#define SPI2_SCLK_I2C3_SCL                           MX8MP_IOMUXC_ECSPI2_SCLK__I2C3_SCL
#define SPI2_SCLK_AUDIOMIX_SAI7_TX_BCLK              MX8MP_IOMUXC_ECSPI2_SCLK__AUDIOMIX_SAI7_TX_BCLK
#define SPI2_SCLK_GPIO5_IO10                         MX8MP_IOMUXC_ECSPI2_SCLK__GPIO5_IO10
#define SPI2_SCLK_GPIO                               MX8MP_IOMUXC_ECSPI2_SCLK__GPIO5_IO10
#define spi2_sclk_gpio   &gpio5 10
#define SPI2_MOSI_ECSPI2_MOSI                        MX8MP_IOMUXC_ECSPI2_MOSI__ECSPI2_MOSI
#define SPI2_MOSI_UART4_DCE_TX                       MX8MP_IOMUXC_ECSPI2_MOSI__UART4_DCE_TX
#define SPI2_MOSI_UART4_DTE_RX                       MX8MP_IOMUXC_ECSPI2_MOSI__UART4_DTE_RX
#define SPI2_MOSI_I2C3_SDA                           MX8MP_IOMUXC_ECSPI2_MOSI__I2C3_SDA
#define SPI2_MOSI_AUDIOMIX_SAI7_TX_DATA00            MX8MP_IOMUXC_ECSPI2_MOSI__AUDIOMIX_SAI7_TX_DATA00
#define SPI2_MOSI_GPIO5_IO11                         MX8MP_IOMUXC_ECSPI2_MOSI__GPIO5_IO11
#define SPI2_MOSI_GPIO                               MX8MP_IOMUXC_ECSPI2_MOSI__GPIO5_IO11
#define spi2_mosi_gpio   &gpio5 11
#define SPI2_MISO_GPIO5_IO12                         MX8MP_IOMUXC_ECSPI2_MISO__GPIO5_IO12
#define SPI2_MISO_GPIO                               MX8MP_IOMUXC_ECSPI2_MISO__GPIO5_IO12
#define spi2_miso_gpio   &gpio5 12
#define SPI2_MISO_ECSPI2_MISO                        MX8MP_IOMUXC_ECSPI2_MISO__ECSPI2_MISO
#define SPI2_MISO_UART4_DCE_CTS                      MX8MP_IOMUXC_ECSPI2_MISO__UART4_DCE_CTS
#define SPI2_MISO_UART4_DTE_RTS                      MX8MP_IOMUXC_ECSPI2_MISO__UART4_DTE_RTS
#define SPI2_MISO_I2C4_SCL                           MX8MP_IOMUXC_ECSPI2_MISO__I2C4_SCL
#define SPI2_MISO_AUDIOMIX_SAI7_MCLK                 MX8MP_IOMUXC_ECSPI2_MISO__AUDIOMIX_SAI7_MCLK
#define SPI2_MISO_CCM_CLKO1                          MX8MP_IOMUXC_ECSPI2_MISO__CCM_CLKO1
#define SPI2_SS0_ECSPI2_SS0                          MX8MP_IOMUXC_ECSPI2_SS0__ECSPI2_SS0
#define SPI2_SS0_UART4_DCE_RTS                       MX8MP_IOMUXC_ECSPI2_SS0__UART4_DCE_RTS
#define SPI2_SS0_UART4_DTE_CTS                       MX8MP_IOMUXC_ECSPI2_SS0__UART4_DTE_CTS
#define SPI2_SS0_I2C4_SDA                            MX8MP_IOMUXC_ECSPI2_SS0__I2C4_SDA
#define SPI2_SS0_CCM_CLKO2                           MX8MP_IOMUXC_ECSPI2_SS0__CCM_CLKO2
#define SPI2_SS0_GPIO5_IO13                          MX8MP_IOMUXC_ECSPI2_SS0__GPIO5_IO13
#define SPI2_SS0_GPIO                                MX8MP_IOMUXC_ECSPI2_SS0__GPIO5_IO13
#define spi2_ss0_gpio   &gpio5 13
#define SPIN94_I2C1_SCL                              MX8MP_IOMUXC_I2C1_SCL__I2C1_SCL
#define SPIN94_ENET_QOS_MDC                          MX8MP_IOMUXC_I2C1_SCL__ENET_QOS_MDC
#define SPIN94_ECSPI1_SCLK                           MX8MP_IOMUXC_I2C1_SCL__ECSPI1_SCLK
#define SPIN94_GPIO5_IO14                            MX8MP_IOMUXC_I2C1_SCL__GPIO5_IO14
#define SPIN94_GPIO                                  MX8MP_IOMUXC_I2C1_SCL__GPIO5_IO14
#define spin94_gpio   &gpio5 14
#define SPIN96_I2C1_SDA                              MX8MP_IOMUXC_I2C1_SDA__I2C1_SDA
#define SPIN96_ENET_QOS_MDIO                         MX8MP_IOMUXC_I2C1_SDA__ENET_QOS_MDIO
#define SPIN96_ECSPI1_MOSI                           MX8MP_IOMUXC_I2C1_SDA__ECSPI1_MOSI
#define SPIN96_GPIO5_IO15                            MX8MP_IOMUXC_I2C1_SDA__GPIO5_IO15
#define SPIN96_GPIO                                  MX8MP_IOMUXC_I2C1_SDA__GPIO5_IO15
#define spin96_gpio   &gpio5 15
#define SPIN196_I2C2_SCL                              MX8MP_IOMUXC_I2C2_SCL__I2C2_SCL
#define SPIN196_ENET_QOS_1588_EVENT1_IN               MX8MP_IOMUXC_I2C2_SCL__ENET_QOS_1588_EVENT1_IN
#define SPIN196_USDHC3_CD_B                           MX8MP_IOMUXC_I2C2_SCL__USDHC3_CD_B
#define SPIN196_ECSPI1_MISO                           MX8MP_IOMUXC_I2C2_SCL__ECSPI1_MISO
#define SPIN196_ENET_QOS_1588_EVENT1_AUX_IN           MX8MP_IOMUXC_I2C2_SCL__ENET_QOS_1588_EVENT1_AUX_IN
#define SPIN196_GPIO5_IO16                            MX8MP_IOMUXC_I2C2_SCL__GPIO5_IO16
#define SPIN196_GPIO                                  MX8MP_IOMUXC_I2C2_SCL__GPIO5_IO16
#define spin196_gpio   &gpio5 16
#define SPIN194_I2C2_SDA                              MX8MP_IOMUXC_I2C2_SDA__I2C2_SDA
#define SPIN194_ENET_QOS_1588_EVENT1_OUT              MX8MP_IOMUXC_I2C2_SDA__ENET_QOS_1588_EVENT1_OUT
#define SPIN194_USDHC3_WP                             MX8MP_IOMUXC_I2C2_SDA__USDHC3_WP
#define SPIN194_ECSPI1_SS0                            MX8MP_IOMUXC_I2C2_SDA__ECSPI1_SS0
#define SPIN194_GPIO5_IO17                            MX8MP_IOMUXC_I2C2_SDA__GPIO5_IO17
#define SPIN194_GPIO                                  MX8MP_IOMUXC_I2C2_SDA__GPIO5_IO17
#define spin194_gpio   &gpio5 17
#define I2C3_SCL_I2C3_SCL                              MX8MP_IOMUXC_I2C3_SCL__I2C3_SCL
#define I2C3_SCL_PWM4_OUT                              MX8MP_IOMUXC_I2C3_SCL__PWM4_OUT
#define I2C3_SCL_GPT2_CLK                              MX8MP_IOMUXC_I2C3_SCL__GPT2_CLK
#define I2C3_SCL_ECSPI2_SCLK                           MX8MP_IOMUXC_I2C3_SCL__ECSPI2_SCLK
#define I2C3_SCL_GPIO5_IO18                            MX8MP_IOMUXC_I2C3_SCL__GPIO5_IO18
#define I2C3_SCL_GPIO                                  MX8MP_IOMUXC_I2C3_SCL__GPIO5_IO18
#define i2c3_scl_gpio   &gpio5 18
#define I2C3_SDA_I2C3_SDA                              MX8MP_IOMUXC_I2C3_SDA__I2C3_SDA
#define I2C3_SDA_PWM3_OUT                              MX8MP_IOMUXC_I2C3_SDA__PWM3_OUT
#define I2C3_SDA_GPT3_CLK                              MX8MP_IOMUXC_I2C3_SDA__GPT3_CLK
#define I2C3_SDA_ECSPI2_MOSI                           MX8MP_IOMUXC_I2C3_SDA__ECSPI2_MOSI
#define I2C3_SDA_GPIO5_IO19                            MX8MP_IOMUXC_I2C3_SDA__GPIO5_IO19
#define I2C3_SDA_GPIO                                  MX8MP_IOMUXC_I2C3_SDA__GPIO5_IO19
#define i2c3_sda_gpio   &gpio5 19
#define SPIN115_I2C4_SCL                              MX8MP_IOMUXC_I2C4_SCL__I2C4_SCL
#define SPIN115_PWM2_OUT                              MX8MP_IOMUXC_I2C4_SCL__PWM2_OUT
#define SPIN115_PCIE_CLKREQ_B                         MX8MP_IOMUXC_I2C4_SCL__PCIE_CLKREQ_B
#define SPIN115_ECSPI2_MISO                           MX8MP_IOMUXC_I2C4_SCL__ECSPI2_MISO
#define SPIN115_GPIO                                  MX8MP_IOMUXC_I2C4_SCL__GPIO5_IO20
#define spin115_gpio   &gpio5 20
#define SPIN121_I2C4_SDA                              MX8MP_IOMUXC_I2C4_SDA__I2C4_SDA
#define SPIN121_PWM1_OUT                              MX8MP_IOMUXC_I2C4_SDA__PWM1_OUT
#define SPIN121_ECSPI2_SS0                            MX8MP_IOMUXC_I2C4_SDA__ECSPI2_SS0
#define SPIN121_GPIO5_IO21                            MX8MP_IOMUXC_I2C4_SDA__GPIO5_IO21
#define SPIN121_GPIO                                  MX8MP_IOMUXC_I2C4_SDA__GPIO5_IO21
#define spin_gpio   &gpio5 21
#define SPIN33_UART1_DCE_RX                         MX8MP_IOMUXC_UART1_RXD__UART1_DCE_RX
#define SPIN33_UART1_DTE_TX                         MX8MP_IOMUXC_UART1_RXD__UART1_DTE_TX
#define SPIN33_ECSPI3_SCLK                          MX8MP_IOMUXC_UART1_RXD__ECSPI3_SCLK
#define SPIN33_GPIO5_IO22                           MX8MP_IOMUXC_UART1_RXD__GPIO5_IO22
#define SPIN33_GPIO                                 MX8MP_IOMUXC_UART1_RXD__GPIO5_IO22
#define spin33_gpio   &gpio5 22
#define SPIN35_UART1_DCE_TX                         MX8MP_IOMUXC_UART1_TXD__UART1_DCE_TX
#define SPIN35_UART1_DTE_RX                         MX8MP_IOMUXC_UART1_TXD__UART1_DTE_RX
#define SPIN35_ECSPI3_MOSI                          MX8MP_IOMUXC_UART1_TXD__ECSPI3_MOSI
#define SPIN35_GPIO5_IO23                           MX8MP_IOMUXC_UART1_TXD__GPIO5_IO23
#define SPIN35_GPIO                                 MX8MP_IOMUXC_UART1_TXD__GPIO5_IO23
#define spin35_gpio   &gpio5 23
#define SPIN36_UART2_DCE_RX                         MX8MP_IOMUXC_UART2_RXD__UART2_DCE_RX
#define SPIN36_UART2_DTE_TX                         MX8MP_IOMUXC_UART2_RXD__UART2_DTE_TX
#define SPIN36_ECSPI3_MISO                          MX8MP_IOMUXC_UART2_RXD__ECSPI3_MISO
#define SPIN36_GPT1_COMPARE3                        MX8MP_IOMUXC_UART2_RXD__GPT1_COMPARE3
#define SPIN36_GPIO5_IO24                           MX8MP_IOMUXC_UART2_RXD__GPIO5_IO24
#define SPIN36_GPIO                                 MX8MP_IOMUXC_UART2_RXD__GPIO5_IO24
#define spin36_gpio   &gpio5 24
#define SPIN38_UART2_DCE_TX                         MX8MP_IOMUXC_UART2_TXD__UART2_DCE_TX
#define SPIN38_UART2_DTE_RX                         MX8MP_IOMUXC_UART2_TXD__UART2_DTE_RX
#define SPIN38_ECSPI3_SS0                           MX8MP_IOMUXC_UART2_TXD__ECSPI3_SS0
#define SPIN38_GPT1_COMPARE2                        MX8MP_IOMUXC_UART2_TXD__GPT1_COMPARE2
#define SPIN38_GPIO5_IO25                           MX8MP_IOMUXC_UART2_TXD__GPIO5_IO25
#define SPIN38_GPIO                                 MX8MP_IOMUXC_UART2_TXD__GPIO5_IO25
#define spin38_gpio   &gpio5 25
#define SPIN27_UART3_DCE_RX                         MX8MP_IOMUXC_UART3_RXD__UART3_DCE_RX
#define SPIN27_UART3_DTE_TX                         MX8MP_IOMUXC_UART3_RXD__UART3_DTE_TX
#define SPIN27_UART1_DCE_CTS                        MX8MP_IOMUXC_UART3_RXD__UART1_DCE_CTS
#define SPIN27_UART1_DTE_RTS                        MX8MP_IOMUXC_UART3_RXD__UART1_DTE_RTS
#define SPIN27_USDHC3_RESET_B                       MX8MP_IOMUXC_UART3_RXD__USDHC3_RESET_B
#define SPIN27_GPT1_CAPTURE2                        MX8MP_IOMUXC_UART3_RXD__GPT1_CAPTURE2
#define SPIN27_CAN2_TX                              MX8MP_IOMUXC_UART3_RXD__CAN2_TX
#define SPIN27_GPIO5_IO26                           MX8MP_IOMUXC_UART3_RXD__GPIO5_IO26
#define SPIN27_GPIO                                 MX8MP_IOMUXC_UART3_RXD__GPIO5_IO26
#define spin27_gpio   &gpio5 26
#define SPIN25_UART3_DCE_TX                         MX8MP_IOMUXC_UART3_TXD__UART3_DCE_TX
#define SPIN25_UART3_DTE_RX                         MX8MP_IOMUXC_UART3_TXD__UART3_DTE_RX
#define SPIN25_UART1_DCE_RTS                        MX8MP_IOMUXC_UART3_TXD__UART1_DCE_RTS
#define SPIN25_UART1_DTE_CTS                        MX8MP_IOMUXC_UART3_TXD__UART1_DTE_CTS
#define SPIN25_USDHC3_VSELECT                       MX8MP_IOMUXC_UART3_TXD__USDHC3_VSELECT
#define SPIN25_GPT1_CLK                             MX8MP_IOMUXC_UART3_TXD__GPT1_CLK
#define SPIN25_CAN2_RX                              MX8MP_IOMUXC_UART3_TXD__CAN2_RX
#define SPIN25_GPIO5_IO27                           MX8MP_IOMUXC_UART3_TXD__GPIO5_IO27
#define SPIN25_GPIO                                 MX8MP_IOMUXC_UART3_TXD__GPIO5_IO27
#define spin25_gpio   &gpio5 27
#define SPIN34_UART4_DCE_RX                         MX8MP_IOMUXC_UART4_RXD__UART4_DCE_RX
#define SPIN34_UART4_DTE_TX                         MX8MP_IOMUXC_UART4_RXD__UART4_DTE_TX
#define SPIN34_UART2_DCE_CTS                        MX8MP_IOMUXC_UART4_RXD__UART2_DCE_CTS
#define SPIN34_UART2_DTE_RTS                        MX8MP_IOMUXC_UART4_RXD__UART2_DTE_RTS
#define SPIN34_PCIE_CLKREQ_B                        MX8MP_IOMUXC_UART4_RXD__PCIE_CLKREQ_B
#define SPIN34_GPT1_COMPARE1                        MX8MP_IOMUXC_UART4_RXD__GPT1_COMPARE1
#define SPIN34_I2C6_SCL                             MX8MP_IOMUXC_UART4_RXD__I2C6_SCL
#define SPIN34_GPIO5_IO28                           MX8MP_IOMUXC_UART4_RXD__GPIO5_IO28
#define SPIN34_GPIO                                 MX8MP_IOMUXC_UART4_RXD__GPIO5_IO28
#define spin34_gpio   &gpio5 28
#define SPIN32_UART4_DCE_TX                         MX8MP_IOMUXC_UART4_TXD__UART4_DCE_TX
#define SPIN32_UART4_DTE_RX                         MX8MP_IOMUXC_UART4_TXD__UART4_DTE_RX
#define SPIN32_UART2_DCE_RTS                        MX8MP_IOMUXC_UART4_TXD__UART2_DCE_RTS
#define SPIN32_UART2_DTE_CTS                        MX8MP_IOMUXC_UART4_TXD__UART2_DTE_CTS
#define SPIN32_GPT1_CAPTURE1                        MX8MP_IOMUXC_UART4_TXD__GPT1_CAPTURE1
#define SPIN32_I2C6_SDA                             MX8MP_IOMUXC_UART4_TXD__I2C6_SDA
#define SPIN32_GPIO5_IO29                           MX8MP_IOMUXC_UART4_TXD__GPIO5_IO29
#define SPIN32_GPIO                                 MX8MP_IOMUXC_UART4_TXD__GPIO5_IO29
#define spin32_gpio   &gpio5 29
#define SPIN130_HDMIMIX_HDMI_SCL                  MX8MP_IOMUXC_HDMI_DDC_SCL__HDMIMIX_HDMI_SCL
#define SPIN130_I2C5_SCL                          MX8MP_IOMUXC_HDMI_DDC_SCL__I2C5_SCL
#define SPIN130_CAN1_TX                           MX8MP_IOMUXC_HDMI_DDC_SCL__CAN1_TX
#define SPIN130_GPIO                              MX8MP_IOMUXC_HDMI_DDC_SCL__GPIO3_IO26
#define spin130_gpio   &gpio3 26
#define SPIN149_HDMIMIX_HDMI_SDA                  MX8MP_IOMUXC_HDMI_DDC_SDA__HDMIMIX_HDMI_SDA
#define SPIN149_I2C5_SDA                          MX8MP_IOMUXC_HDMI_DDC_SDA__I2C5_SDA
#define SPIN149_CAN1_RX                           MX8MP_IOMUXC_HDMI_DDC_SDA__CAN1_RX
#define SPIN149_GPIO3_IO27                        MX8MP_IOMUXC_HDMI_DDC_SDA__GPIO3_IO27
#define SPIN149_GPIO                              MX8MP_IOMUXC_HDMI_DDC_SDA__GPIO3_IO27
#define spin149_gpio   &gpio3 27
#define BPIN54_HDMIMIX_HDMI_CEC                      MX8MP_IOMUXC_HDMI_CEC__HDMIMIX_HDMI_CEC
#define BPIN54_I2C6_SCL                              MX8MP_IOMUXC_HDMI_CEC__I2C6_SCL
#define BPIN54_CAN2_TX                               MX8MP_IOMUXC_HDMI_CEC__CAN2_TX
#define BPIN54_GPIO3_IO28                            MX8MP_IOMUXC_HDMI_CEC__GPIO3_IO28
#define BPIN54_GPIO                                  MX8MP_IOMUXC_HDMI_CEC__GPIO3_IO28
#define bpin54_gpio   &gpio3 28
#define BPIN48_HDMIMIX_HDMI_HPD                      MX8MP_IOMUXC_HDMI_HPD__HDMIMIX_HDMI_HPD
#define BPIN48_AUDIOMIX_HDMI_HPD_O                   MX8MP_IOMUXC_HDMI_HPD__AUDIOMIX_HDMI_HPD_O
#define BPIN48_I2C6_SDA                              MX8MP_IOMUXC_HDMI_HPD__I2C6_SDA
#define BPIN48_CAN2_RX                               MX8MP_IOMUXC_HDMI_HPD__CAN2_RX
#define BPIN48_GPIO3_IO29                            MX8MP_IOMUXC_HDMI_HPD__GPIO3_IO29
#define BPIN48_GPIO                                  MX8MP_IOMUXC_HDMI_HPD__GPIO3_IO29
#define bpin48_gpio   &gpio3 29


#endif /* __DTS_IMX8MP_PINFUNC_H */
